// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("capmas_heads")]
public partial class CapmasHead
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("statement")]
    public string Statement { get; set; }

    [Column("image_url")]
    public string ImageUrl { get; set; }

    [Column("start_year")]
    public int StartYear { get; set; }

    [Column("end_year")]
    public int? EndYear { get; set; }

    [Column("is_current")]
    public bool IsCurrent { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Required]
    [Column("is_system")]
    public bool? IsSystem { get; set; }

    [InverseProperty("CapmasHead")]
    public virtual ICollection<CapmasHeadTranslation> CapmasHeadTranslations { get; set; } = new List<CapmasHeadTranslation>();
}