// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("data_requests")]
[Index("UserId", Name = "IX_data_requests_user_id")]
public partial class DataRequest
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("employeer")]
    [StringLength(255)]
    public string Employeer { get; set; }

    [Required]
    [Column("required_information")]
    [StringLength(255)]
    public string RequiredInformation { get; set; }

    [Required]
    [Column("user_id")]
    public string UserId { get; set; }

    [Column("purpose_of_requesting_data")]
    public int PurposeOfRequestingData { get; set; }

    [Column("form_of_data_requested")]
    public int FormOfDataRequested { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }
}