// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("department_users")]
[Index("DepartmentId", Name = "IX_department_users_department_id")]
public partial class DepartmentUser
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_id")]
    public string UserId { get; set; }

    [Column("department_id")]
    public long DepartmentId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Required]
    [Column("is_manager")]
    public bool? IsManager { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("DepartmentUsers")]
    public virtual Department Department { get; set; }
}