// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("egypt_population")]
public partial class EgyptPopulation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("population")]
    public double Population { get; set; }

    [Column("population_density")]
    public double PopulationDensity { get; set; }

    [Column("date")]
    public DateTime Date { get; set; }
}