// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("egypt_statistics_journal_translations")]
[Index("EgyptStatisticsJournalId", "Locale", Name = "IX_egypt_statistics_journal_translations_egypt_statistics_journal_id_locale", IsUnique = true)]
public partial class EgyptStatisticsJournalTranslation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Required]
    [Column("locale")]
    [StringLength(6)]
    public string Locale { get; set; }

    [Column("egypt_statistics_journal_id")]
    public long EgyptStatisticsJournalId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("pdf_url")]
    public string PdfUrl { get; set; }

    [ForeignKey("EgyptStatisticsJournalId")]
    [InverseProperty("EgyptStatisticsJournalTranslations")]
    public virtual EgyptStatisticsJournal EgyptStatisticsJournal { get; set; }
}