// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("email_list_categories")]
[Index("Name", Name = "IX_email_list_categories_name", IsUnique = true)]
public partial class EmailListCategory
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [InverseProperty("EmailListCategory")]
    public virtual ICollection<EmailListCategoryTranslation> EmailListCategoryTranslations { get; set; } = new List<EmailListCategoryTranslation>();

    [InverseProperty("EmailListCategory")]
    public virtual ICollection<EmailList> EmailLists { get; set; } = new List<EmailList>();

    [InverseProperty("EmailListCategory")]
    public virtual ICollection<NewsEmailListCategory> NewsEmailListCategories { get; set; } = new List<NewsEmailListCategory>();
}