// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("email_lists")]
[Index("Email", "EmailListCategoryId", Name = "IX_email_lists_email_email_list_category_id", IsUnique = true)]
[Index("EmailListCategoryId", Name = "IX_email_lists_email_list_category_id")]
public partial class EmailList
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("email")]
    public string Email { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("email_list_category_id")]
    public long EmailListCategoryId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("EmailListCategoryId")]
    [InverseProperty("EmailLists")]
    public virtual EmailListCategory EmailListCategory { get; set; }
}