// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("events")]
[Index("EventTypeId", Name = "IX_events_event_type_id")]
public partial class Event
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("image")]
    public string Image { get; set; }

    [Column("agenda")]
    public string Agenda { get; set; }

    [Column("speaker")]
    public string Speaker { get; set; }

    [Column("event_type_id")]
    public long? EventTypeId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<Calendar> Calendars { get; set; } = new List<Calendar>();

    [InverseProperty("Event")]
    public virtual ICollection<EventTranslation> EventTranslations { get; set; } = new List<EventTranslation>();

    [ForeignKey("EventTypeId")]
    [InverseProperty("Events")]
    public virtual EventType EventType { get; set; }
}