// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("evidence_and_classification_translations")]
[Index("EvidenceAndClassificationId", "Locale", Name = "IX_evidence_and_classification_translations_evidence_and_classification_id_locale", IsUnique = true)]
public partial class EvidenceAndClassificationTranslation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("locale")]
    [StringLength(6)]
    public string Locale { get; set; }

    [Column("evidence_and_classification_id")]
    public long EvidenceAndClassificationId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("EvidenceAndClassificationId")]
    [InverseProperty("EvidenceAndClassificationTranslations")]
    public virtual EvidenceAndClassification EvidenceAndClassification { get; set; }
}