// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("governorates")]
[Index("Name", Name = "IX_governorates_name", IsUnique = true)]
public partial class Governorate
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("code")]
    public string Code { get; set; }

    [Column("lat")]
    public long Lat { get; set; }

    [Column("lng")]
    public long Lng { get; set; }

    [Column("capital")]
    public long Capital { get; set; }

    [Column("area")]
    public double Area { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [Required]
    [Column("is_system")]
    public bool? IsSystem { get; set; }

    [InverseProperty("Governorate")]
    public virtual ICollection<GovernoratePopulation> GovernoratePopulations { get; set; } = new List<GovernoratePopulation>();

    [InverseProperty("Governorate")]
    public virtual ICollection<GovernorateTranslation> GovernorateTranslations { get; set; } = new List<GovernorateTranslation>();

    [InverseProperty("Governorate")]
    public virtual ICollection<RegionalOffice> RegionalOffices { get; set; } = new List<RegionalOffice>();
}