// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("journalisms")]
[Index("JournalCategoryId", Name = "IX_journalisms_journal_category_id")]
public partial class Journalism
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("link")]
    public string Link { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Column("publish_date")]
    public DateTime PublishDate { get; set; }

    [Column("journal_category_id")]
    public long JournalCategoryId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [ForeignKey("JournalCategoryId")]
    [InverseProperty("Journalisms")]
    public virtual JournalCategory JournalCategory { get; set; }

    [InverseProperty("Journalism")]
    public virtual ICollection<JournalismTranslation> JournalismTranslations { get; set; } = new List<JournalismTranslation>();
}