// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("microfilm_data")]
[Index("AgencyTypeId", Name = "IX_microfilm_data_agency_type_id")]
[Index("FilmTypeId", Name = "IX_microfilm_data_film_type_id")]
[Index("UserId", Name = "IX_microfilm_data_user_id")]
public partial class MicrofilmDatum
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("agency_name")]
    [StringLength(255)]
    public string AgencyName { get; set; }

    [Column("agency_type_id")]
    public long AgencyTypeId { get; set; }

    [Column("film_type_id")]
    public long FilmTypeId { get; set; }

    [Column("film_count")]
    public int FilmCount { get; set; }

    [Required]
    [Column("user_id")]
    public string UserId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("AgencyTypeId")]
    [InverseProperty("MicrofilmData")]
    public virtual AgencyType AgencyType { get; set; }

    [ForeignKey("FilmTypeId")]
    [InverseProperty("MicrofilmData")]
    public virtual FilmType FilmType { get; set; }
}