// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("news_categories")]
[Index("CategoryId", Name = "IX_news_categories_category_id")]
[Index("NewsId", "CategoryId", Name = "IX_news_categories_news_id_category_id", IsUnique = true)]
public partial class NewsCategory
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("category_id")]
    public long CategoryId { get; set; }

    [Column("news_id")]
    public long NewsId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("NewsCategories")]
    public virtual Category Category { get; set; }

    [ForeignKey("NewsId")]
    [InverseProperty("NewsCategories")]
    public virtual News News { get; set; }
}