// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("news_tags")]
[Index("NewsId", Name = "IX_news_tags_news_id")]
[Index("TagId", Name = "IX_news_tags_tag_id")]
public partial class NewsTag
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("tag_id")]
    public long TagId { get; set; }

    [Column("news_id")]
    public long NewsId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [ForeignKey("NewsId")]
    [InverseProperty("NewsTags")]
    public virtual News News { get; set; }

    [ForeignKey("TagId")]
    [InverseProperty("NewsTags")]
    public virtual Tag Tag { get; set; }
}