// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("news")]
[Index("PublicationDetailId", Name = "IX_news_publication_detail_id")]
[Index("SubSubjectId", Name = "IX_news_sub_subject_id")]
public partial class News
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    [StringLength(100)]
    public string Title { get; set; }

    [Column("brief")]
    [StringLength(255)]
    public string Brief { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Column("image")]
    public string Image { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [Column("is_internal")]
    public bool IsInternal { get; set; }

    [Column("is_pinned")]
    public bool IsPinned { get; set; }

    [Column("home_page")]
    public bool HomePage { get; set; }

    [Column("order")]
    public int? Order { get; set; }

    [Column("no_views")]
    public int? NoViews { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Required]
    [Column("is_pdf")]
    public bool? IsPdf { get; set; }

    [Column("pdf_url")]
    public string PdfUrl { get; set; }

    [Column("publication_detail_id")]
    public long? PublicationDetailId { get; set; }

    [Column("sub_subject_id")]
    public long? SubSubjectId { get; set; }

    [Required]
    [Column("is_send")]
    public bool? IsSend { get; set; }

    [InverseProperty("News")]
    public virtual ICollection<NewsCategory> NewsCategories { get; set; } = new List<NewsCategory>();

    [InverseProperty("News")]
    public virtual ICollection<NewsEmailListCategory> NewsEmailListCategories { get; set; } = new List<NewsEmailListCategory>();

    [InverseProperty("News")]
    public virtual ICollection<NewsTag> NewsTags { get; set; } = new List<NewsTag>();

    [InverseProperty("News")]
    public virtual ICollection<NewsTranslation> NewsTranslations { get; set; } = new List<NewsTranslation>();

    [ForeignKey("PublicationDetailId")]
    [InverseProperty("News")]
    public virtual PublicationDetail PublicationDetail { get; set; }

    [ForeignKey("SubSubjectId")]
    [InverseProperty("News")]
    public virtual Subject SubSubject { get; set; }
}