// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("news_translations")]
[Index("NewsId", "Locale", Name = "IX_news_translations_news_id_locale", IsUnique = true)]
public partial class NewsTranslation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    [StringLength(150)]
    public string Title { get; set; }

    [Column("brief")]
    [StringLength(256)]
    public string Brief { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Required]
    [Column("locale")]
    [StringLength(6)]
    public string Locale { get; set; }

    [Column("news_id")]
    public long NewsId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("pdf_url")]
    public string PdfUrl { get; set; }

    [ForeignKey("NewsId")]
    [InverseProperty("NewsTranslations")]
    public virtual News News { get; set; }
}