// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("photos")]
[Index("PhotoAlbumId", Name = "IX_photos_photo_album_id")]
public partial class Photo
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("thumbnail")]
    public string Thumbnail { get; set; }

    [Column("is_pinned")]
    public bool IsPinned { get; set; }

    [Column("image")]
    public string Image { get; set; }

    [Column("photo_album_id")]
    public long PhotoAlbumId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("PhotoAlbumId")]
    [InverseProperty("Photos")]
    public virtual PhotoAlbum PhotoAlbum { get; set; }
}