// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("publication_details")]
[Index("PublicationId", Name = "IX_publication_details_publication_id")]
[Index("StudyPeriodId", Name = "IX_publication_details_study_period_id")]
public partial class PublicationDetail
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("pdf_url")]
    public string PdfUrl { get; set; }

    [Column("excel_url")]
    public string ExcelUrl { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [Column("publication_id")]
    public long PublicationId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("month")]
    public int? Month { get; set; }

    [Column("quarter")]
    public int? Quarter { get; set; }

    [Column("year")]
    public int Year { get; set; }

    [Column("publication_cover")]
    public string PublicationCover { get; set; }

    [Required]
    [Column("is_home")]
    public bool? IsHome { get; set; }

    [Column("release_date")]
    public DateTime ReleaseDate { get; set; }

    [Column("study_period_id")]
    public long? StudyPeriodId { get; set; }

    [InverseProperty("PublicationDetail")]
    public virtual ICollection<Infographic> Infographics { get; set; } = new List<Infographic>();

    [InverseProperty("PublicationDetail")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [ForeignKey("PublicationId")]
    [InverseProperty("PublicationDetails")]
    public virtual Publication Publication { get; set; }

    [InverseProperty("PublicationDetail")]
    public virtual ICollection<PublicationIndicator> PublicationIndicators { get; set; } = new List<PublicationIndicator>();

    [ForeignKey("StudyPeriodId")]
    [InverseProperty("PublicationDetails")]
    public virtual StudyPeriod StudyPeriod { get; set; }
}