// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("publication_subscriptions")]
[Index("PublicationId", Name = "IX_publication_subscriptions_publication_id")]
[Index("UserId", "PublicationId", Name = "IX_publication_subscriptions_user_id_publication_id", IsUnique = true)]
public partial class PublicationSubscription
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("publication_id")]
    public long PublicationId { get; set; }

    [Required]
    [Column("user_id")]
    public string UserId { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [ForeignKey("PublicationId")]
    [InverseProperty("PublicationSubscriptions")]
    public virtual Publication Publication { get; set; }
}