// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("regional_office")]
[Index("GovernorateId", Name = "IX_regional_office_governorate_id")]
public partial class RegionalOffice
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("address")]
    public string Address { get; set; }

    [Column("phone_number")]
    public string PhoneNumber { get; set; }

    [Column("mail")]
    public string Mail { get; set; }

    [Column("latitude")]
    public double Latitude { get; set; }

    [Column("longitude")]
    public double Longitude { get; set; }

    [Column("is_main_location")]
    public bool IsMainLocation { get; set; }

    [Column("governorate_id")]
    public long? GovernorateId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [Required]
    [Column("is_system")]
    public bool? IsSystem { get; set; }

    [ForeignKey("GovernorateId")]
    [InverseProperty("RegionalOffices")]
    public virtual Governorate Governorate { get; set; }

    [InverseProperty("RegionalOffice")]
    public virtual ICollection<RegionalOfficeTranslation> RegionalOfficeTranslations { get; set; } = new List<RegionalOfficeTranslation>();
}