// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("services_and_tools")]
[Index("DepartmentId", Name = "IX_services_and_tools_department_id")]
public partial class ServicesAndTool
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("image")]
    public string Image { get; set; }

    [Column("short_description")]
    [StringLength(256)]
    public string ShortDescription { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Column("link")]
    public string Link { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Required]
    [Column("is_internal")]
    public bool? IsInternal { get; set; }

    [Required]
    [Column("is_homepage")]
    public bool? IsHomepage { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [Column("department_id")]
    public long? DepartmentId { get; set; }

    [Required]
    [Column("is_system")]
    public bool? IsSystem { get; set; }

    [Column("about")]
    public string About { get; set; }

    [Required]
    [Column("is_new")]
    public bool? IsNew { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("ServicesAndTools")]
    public virtual Department Department { get; set; }

    [InverseProperty("ServiceAndTool")]
    public virtual ICollection<ServiceAndToolTranslation> ServiceAndToolTranslations { get; set; } = new List<ServiceAndToolTranslation>();
}