// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("service_and_tool_translations")]
[Index("ServiceAndToolId", "Locale", Name = "IX_service_and_tool_translations_service_and_tool_id_locale", IsUnique = true)]
public partial class ServiceAndToolTranslation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("short_description")]
    [StringLength(256)]
    public string ShortDescription { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Required]
    [Column("locale")]
    [StringLength(6)]
    public string Locale { get; set; }

    [Column("service_and_tool_id")]
    public long ServiceAndToolId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("about")]
    public string About { get; set; }

    [ForeignKey("ServiceAndToolId")]
    [InverseProperty("ServiceAndToolTranslations")]
    public virtual ServicesAndTool ServiceAndTool { get; set; }
}