// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("survey_question_option")]
[Index("SurveyQuestionId", Name = "IX_survey_question_option_survey_question_id")]
public partial class SurveyQuestionOption
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("order")]
    public int? Order { get; set; }

    [Column("voters")]
    public int Voters { get; set; }

    [Column("vote_percent", TypeName = "decimal(18, 2)")]
    public decimal VotePercent { get; set; }

    [Column("survey_question_id")]
    public long SurveyQuestionId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [ForeignKey("SurveyQuestionId")]
    [InverseProperty("SurveyQuestionOptions")]
    public virtual SurveyQuestion SurveyQuestion { get; set; }

    [InverseProperty("SurveyQuestionOption")]
    public virtual ICollection<SurveyQuestionOptionTranslation> SurveyQuestionOptionTranslations { get; set; } = new List<SurveyQuestionOptionTranslation>();

    [InverseProperty("SurveyQuestionOption")]
    public virtual ICollection<SurveyQuestionOptionVote> SurveyQuestionOptionVotes { get; set; } = new List<SurveyQuestionOptionVote>();
}