// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("survey_question_option_vote ")]
[Index("SurveyQuestionId", Name = "IX_survey_question_option_vote _survey_question_id")]
[Index("SurveyQuestionOptionId", Name = "IX_survey_question_option_vote _survey_question_option_id")]
[Index("SurveyVoteId", Name = "IX_survey_question_option_vote _survey_vote_id")]
public partial class SurveyQuestionOptionVote
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("survey_question_id")]
    public long SurveyQuestionId { get; set; }

    [Column("survey_question_option_id")]
    public long SurveyQuestionOptionId { get; set; }

    [Column("survey_vote_id")]
    public long SurveyVoteId { get; set; }

    [ForeignKey("SurveyQuestionId")]
    [InverseProperty("SurveyQuestionOptionVotes")]
    public virtual SurveyQuestion SurveyQuestion { get; set; }

    [ForeignKey("SurveyQuestionOptionId")]
    [InverseProperty("SurveyQuestionOptionVotes")]
    public virtual SurveyQuestionOption SurveyQuestionOption { get; set; }

    [ForeignKey("SurveyVoteId")]
    [InverseProperty("SurveyQuestionOptionVotes")]
    public virtual SurveyVote SurveyVote { get; set; }
}