// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("survey_censuse_translation")]
[Index("SurveyCensuseId", "Locale", Name = "IX_survey_censuse_translation_survey_censuse_id_locale", IsUnique = true)]
public partial class SurveyCensuseTranslation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Required]
    [Column("locale")]
    [StringLength(6)]
    public string Locale { get; set; }

    [Column("survey_censuse_id")]
    public long SurveyCensuseId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("SurveyCensuseId")]
    [InverseProperty("SurveyCensuseTranslations")]
    public virtual SurveyCensuse SurveyCensuse { get; set; }
}