// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("survey_question")]
[Index("SurveyId", Name = "IX_survey_question_SurveyId")]
public partial class SurveyQuestion
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("order")]
    public int? Order { get; set; }

    [Column("question_type")]
    public int QuestionType { get; set; }

    public long SurveyId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [ForeignKey("SurveyId")]
    [InverseProperty("SurveyQuestions")]
    public virtual Survey Survey { get; set; }

    [InverseProperty("SurveyQuestion")]
    public virtual ICollection<SurveyQuestionOptionVote> SurveyQuestionOptionVotes { get; set; } = new List<SurveyQuestionOptionVote>();

    [InverseProperty("SurveyQuestion")]
    public virtual ICollection<SurveyQuestionOption> SurveyQuestionOptions { get; set; } = new List<SurveyQuestionOption>();

    [InverseProperty("SurveyQuestion")]
    public virtual ICollection<SurveyQuestionTranslation> SurveyQuestionTranslations { get; set; } = new List<SurveyQuestionTranslation>();
}