// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("training_program")]
public partial class TrainingProgram
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("no_hours")]
    public int NoHours { get; set; }

    [Column("price", TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Column("image")]
    public string Image { get; set; }

    [Column("attachment")]
    public string Attachment { get; set; }

    [Column("start_date")]
    public DateTime? StartDate { get; set; }

    [Column("end_date")]
    public DateTime? EndDate { get; set; }

    [Column("no_repeat")]
    public int? NoRepeat { get; set; }

    [Column("no_seats")]
    public int? NoSeats { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [InverseProperty("TrainingProgram")]
    public virtual ICollection<TrainingProgramApplication> TrainingProgramApplications { get; set; } = new List<TrainingProgramApplication>();

    [InverseProperty("TrainingProgram")]
    public virtual ICollection<TrainingProgramTranslation> TrainingProgramTranslations { get; set; } = new List<TrainingProgramTranslation>();
}