// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("training_program_application")]
[Index("TrainingProgramId", Name = "IX_training_program_application_training_program_id")]
public partial class TrainingProgramApplication
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("address")]
    public string Address { get; set; }

    [Column("phone_number")]
    public string PhoneNumber { get; set; }

    [Column("email")]
    public string Email { get; set; }

    [Column("applying_date")]
    public DateTime ApplyingDate { get; set; }

    [Column("gender")]
    public int Gender { get; set; }

    [Column("birth_date")]
    public DateTime? BirthDate { get; set; }

    [Column("training_program_id")]
    public long TrainingProgramId { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [ForeignKey("TrainingProgramId")]
    [InverseProperty("TrainingProgramApplications")]
    public virtual TrainingProgram TrainingProgram { get; set; }
}