// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("user_security_questions")]
[Index("SecurityQuestionId", Name = "user_security_question_security_question_id_foreign")]
[Index("UserId", Name = "user_security_question_user_id_foreign")]
public partial class UserSecurityQuestion
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_id")]
    public string UserId { get; set; }

    [Column("security_question_id")]
    public long SecurityQuestionId { get; set; }

    [Column("security_answer")]
    [StringLength(255)]
    public string SecurityAnswer { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("SecurityQuestionId")]
    [InverseProperty("UserSecurityQuestions")]
    public virtual SecurityQuestion SecurityQuestion { get; set; }
}