// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Capmas_Test;

[Table("video_library")]
[Index("VideoLibraryCategoryId", Name = "IX_video_library_video_library_category_id")]
public partial class VideoLibrary
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("publishing_date")]
    public DateTime PublishingDate { get; set; }

    [Column("url")]
    public string Url { get; set; }

    [Column("is_pinned")]
    public bool IsPinned { get; set; }

    [Column("video_type")]
    public int VideoType { get; set; }

    [Column("video_library_category_id")]
    public long VideoLibraryCategoryId { get; set; }

    [Column("created_by")]
    public string CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_by")]
    public string UpdatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("is_published")]
    public bool IsPublished { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }

    [Column("publish_date")]
    public DateTime? PublishDate { get; set; }

    [ForeignKey("VideoLibraryCategoryId")]
    [InverseProperty("VideoLibraries")]
    public virtual VideoLibraryCategory VideoLibraryCategory { get; set; }

    [InverseProperty("MediaFileCategory")]
    public virtual ICollection<VideoLibraryTranslation> VideoLibraryTranslations { get; set; } = new List<VideoLibraryTranslation>();
}