// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("catogry")]
public partial class Catogry
{
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(200)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("MSM_ID")]
    public int? MsmId { get; set; }
}