// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("catogry_all")]
public partial class CatogryAll
{
    [Column("id")]
    public int Id { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("cat_sub")]
    public int CatSub { get; set; }

    [Column("cat_group")]
    public int? CatGroup { get; set; }

    [Column("gov")]
    [StringLength(200)]
    [Unicode(false)]
    public string Gov { get; set; }

    [Column("stat_year")]
    [StringLength(11)]
    [Unicode(false)]
    public string StatYear { get; set; }

    [Column("issu_year")]
    public int? IssuYear { get; set; }

    [Column("issu_month")]
    public int? IssuMonth { get; set; }

    [Column("img")]
    [StringLength(50)]
    [Unicode(false)]
    public string Img { get; set; }

    [Column("pdf")]
    [StringLength(150)]
    [Unicode(false)]
    public string Pdf { get; set; }
}