// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("Channel")]
public partial class Channel
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [StringLength(50)]
    public string Link { get; set; }

    [Required]
    [StringLength(100)]
    public string Copyright { get; set; }

    [InverseProperty("Channel")]
    public virtual ICollection<Feed> Feeds { get; set; } = new List<Feed>();
}