// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("CommandLog")]
public partial class CommandLog
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(128)]
    public string DatabaseName { get; set; }

    [StringLength(128)]
    public string SchemaName { get; set; }

    [StringLength(128)]
    public string ObjectName { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string ObjectType { get; set; }

    [StringLength(128)]
    public string IndexName { get; set; }

    public byte? IndexType { get; set; }

    [StringLength(128)]
    public string StatisticsName { get; set; }

    public int? PartitionNumber { get; set; }

    [Column(TypeName = "xml")]
    public string ExtendedInfo { get; set; }

    [Required]
    public string Command { get; set; }

    [Required]
    [StringLength(60)]
    public string CommandType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    public int? ErrorNumber { get; set; }

    public string ErrorMessage { get; set; }
}