// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("GIS_BuildOld")]
public partial class GisBuildOld1
{
    [Key]
    [Column("BUILD_ID")]
    public int BuildId { get; set; }

    [Column("UNITCODE")]
    [StringLength(255)]
    public string Unitcode { get; set; }

    [Column("SSEC_COD_4")]
    [StringLength(4)]
    public string SsecCod4 { get; set; }

    [Column("LAY")]
    public int? Lay { get; set; }

    [Column("ADDR1_2016")]
    public int? Addr12016 { get; set; }

    [Column("ADDR3_2016")]
    [StringLength(150)]
    public string Addr32016 { get; set; }

    [Column("NAME_2016")]
    [StringLength(200)]
    public string Name2016 { get; set; }

    [Column("UNIQE_CODE_2016")]
    [StringLength(12)]
    public string UniqeCode2016 { get; set; }

    [Column("OWNER")]
    [StringLength(150)]
    public string Owner { get; set; }

    [Column("SUB_LAY_TY")]
    public short? SubLayTy { get; set; }
}