// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("gis_bound_data_desc")]
public partial class GisBoundDataDesc
{
    [Column("OBJECTID")]
    public int Objectid { get; set; }

    [Column("code")]
    public short? Code { get; set; }

    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("disc")]
    [StringLength(50)]
    public string Disc { get; set; }

    [Column("section_code")]
    public short? SectionCode { get; set; }

    [Column("Desc_EN")]
    [StringLength(200)]
    [Unicode(false)]
    public string DescEn { get; set; }
}