// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("gis_data_sections")]
public partial class GisDataSection
{
    [Column("OBJECTID")]
    public int Objectid { get; set; }

    [Column("data_section_code")]
    public short? DataSectionCode { get; set; }

    [Column("data_section_name")]
    [StringLength(150)]
    public string DataSectionName { get; set; }

    [Column("data_section_order")]
    public short? DataSectionOrder { get; set; }
}