// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("GIS_GOVERNORATES")]
public partial class GisGovernorate
{
    [Key]
    [Column("GOV_ID")]
    public int GovId { get; set; }

    [Column("GOV_NAME_E")]
    [StringLength(50)]
    public string GovNameE { get; set; }

    [Column("GOV_CODE")]
    [StringLength(50)]
    public string GovCode { get; set; }

    [Column("GOV_NAME_A")]
    [StringLength(50)]
    public string GovNameA { get; set; }
}