// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("gis_kism_data__")]
public partial class GisKismDatum2
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("OBJECTID")]
    [StringLength(255)]
    public string Objectid { get; set; }

    [Column("pop_no")]
    [StringLength(255)]
    public string PopNo { get; set; }

    [Column("birth_no")]
    public double? BirthNo { get; set; }

    [Column("death_no")]
    public double? DeathNo { get; set; }

    [Column("mar_no")]
    public double? MarNo { get; set; }

    [Column("devor_no")]
    public double? DevorNo { get; set; }

    [Column("un_employ_no")]
    [StringLength(255)]
    public string UnEmployNo { get; set; }

    [Column("work_injur_no")]
    public double? WorkInjurNo { get; set; }

    [Column("wages")]
    [StringLength(255)]
    public string Wages { get; set; }

    [Column("work_hours")]
    [StringLength(255)]
    public string WorkHours { get; set; }

    [Column("trading_ersta_all")]
    [StringLength(255)]
    public string TradingErstaAll { get; set; }

    [Column("trading_estab_part")]
    [StringLength(255)]
    public string TradingEstabPart { get; set; }

    [Column("iron_factories_no")]
    [StringLength(255)]
    public string IronFactoriesNo { get; set; }

    [Column("asmant_factories_no")]
    [StringLength(255)]
    public string AsmantFactoriesNo { get; set; }

    [Column("home_device_factories")]
    [StringLength(255)]
    public string HomeDeviceFactories { get; set; }

    [Column("electric_station_no")]
    [StringLength(255)]
    public string ElectricStationNo { get; set; }

    [Column("tourist_arrivals_no")]
    [StringLength(255)]
    public string TouristArrivalsNo { get; set; }

    [Column("tourist_departing_no")]
    [StringLength(255)]
    public string TouristDepartingNo { get; set; }

    [Column("tourist_days_no")]
    [StringLength(255)]
    public string TouristDaysNo { get; set; }

    [Column("hotels_no")]
    public double? HotelsNo { get; set; }

    [Column("hospitals_no")]
    public double? HospitalsNo { get; set; }

    [Column("ambulance_no")]
    public double? AmbulanceNo { get; set; }

    [Column("clubs_no")]
    public double? ClubsNo { get; set; }

    [Column("NOG_no")]
    public double? NogNo { get; set; }

    [Column("water_amount")]
    [StringLength(255)]
    public string WaterAmount { get; set; }

    [Column("residenttial_units")]
    [StringLength(255)]
    public string ResidenttialUnits { get; set; }

    [Column("beaches_no")]
    [StringLength(255)]
    public string BeachesNo { get; set; }

    [Column("parks_no")]
    [StringLength(255)]
    public string ParksNo { get; set; }

    [Column("garbage")]
    public double? Garbage { get; set; }

    [Column("lamps_no")]
    [StringLength(255)]
    public string LampsNo { get; set; }

    [Column("ponds_no")]
    [StringLength(255)]
    public string PondsNo { get; set; }

    [Column("tape_no")]
    public double? TapeNo { get; set; }

    [Column("markets_no")]
    [StringLength(255)]
    public string MarketsNo { get; set; }

    [Column("vehicles_no")]
    [StringLength(255)]
    public string VehiclesNo { get; set; }

    [Column("schools_no")]
    public double? SchoolsNo { get; set; }

    [Column("universities_no")]
    public double? UniversitiesNo { get; set; }

    [Column("institutes_no")]
    [StringLength(255)]
    public string InstitutesNo { get; set; }

    [Column("class_capasity")]
    [StringLength(255)]
    public string ClassCapasity { get; set; }

    [Column("crop_area")]
    [StringLength(255)]
    public string CropArea { get; set; }

    [Column("cultivated_area")]
    [StringLength(255)]
    public string CultivatedArea { get; set; }

    [Column("crops")]
    [StringLength(255)]
    public string Crops { get; set; }

    [Column("water_used")]
    [StringLength(255)]
    public string WaterUsed { get; set; }

    [Column("cattle")]
    [StringLength(255)]
    public string Cattle { get; set; }

    [Column("crops_production")]
    [StringLength(255)]
    public string CropsProduction { get; set; }

    [Column("gov")]
    [StringLength(2)]
    public string Gov { get; set; }

    [Column("sec")]
    [StringLength(4)]
    public string Sec { get; set; }

    [Column("gov_code")]
    [StringLength(255)]
    public string GovCode { get; set; }

    [Column("sec_code")]
    [StringLength(255)]
    public string SecCode { get; set; }

    [Column("garbage_q")]
    public double? GarbageQ { get; set; }

    [Column("garbage_w")]
    public double? GarbageW { get; set; }
}