// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("GIS_Poverty_All_Subsec")]
public partial class GisPovertyAllSubsec
{
    [Column("OBJECTID")]
    public int Objectid { get; set; }

    [Column("gov_code")]
    [StringLength(2)]
    public string GovCode { get; set; }

    [Column("sec_code")]
    [StringLength(4)]
    public string SecCode { get; set; }

    [Column("poor_people")]
    public double? PoorPeople { get; set; }

    [Column("Poverty_Gap")]
    public double? PovertyGap { get; set; }

    [Column("Gin_coefficien")]
    public double? GinCoefficien { get; set; }

    [Column("per_capita_consumption")]
    public double? PerCapitaConsumption { get; set; }

    [Column("No_of_the_poor")]
    public double? NoOfThePoor { get; set; }

    [Column("Households_2006")]
    public double? Households2006 { get; set; }

    [Column("Population_2006")]
    public double? Population2006 { get; set; }

    [Column("Population_2013")]
    public double? Population2013 { get; set; }

    [Column("urban")]
    [StringLength(5)]
    public string Urban { get; set; }

    [Column("id_section")]
    public double? IdSection { get; set; }

    [Column("Gov_Name")]
    [StringLength(100)]
    public string GovName { get; set; }

    [Column("Qism_Markaz_Name")]
    [StringLength(100)]
    public string QismMarkazName { get; set; }

    [Column("Shyakha_village_Name")]
    [StringLength(100)]
    public string ShyakhaVillageName { get; set; }

    [Column("Prop_estab_less_6_emp")]
    public double? PropEstabLess6Emp { get; set; }

    [Column("Prop_estab_from_6_to_20_emp")]
    public double? PropEstabFrom6To20Emp { get; set; }

    [Column("public_private_hosp")]
    public double? PublicPrivateHosp { get; set; }

    [Column("Youth_Club")]
    public double? YouthClub { get; set; }

    [Column("Mosq_churches")]
    public double? MosqChurches { get; set; }

    public double? Banks { get; set; }

    [Column("Police_offices")]
    public double? PoliceOffices { get; set; }

    [Column("Post_offices")]
    public double? PostOffices { get; set; }

    [Column("hosp_count")]
    public double? HospCount { get; set; }

    [Column("health_unit_count")]
    public double? HealthUnitCount { get; set; }

    [Column("ambulance_count")]
    public double? AmbulanceCount { get; set; }

    [Column("Per_female_headed_households")]
    public double? PerFemaleHeadedHouseholds { get; set; }

    [Column("Avrg_No_Childern_Household")]
    public double? AvrgNoChildernHousehold { get; set; }

    [Column("Avrg_No_Adult_Males_Household")]
    public double? AvrgNoAdultMalesHousehold { get; set; }

    [Column("Avrg_No_Adult_Females_Household")]
    public double? AvrgNoAdultFemalesHousehold { get; set; }

    [Column("Avrg_No_Elderly_Household")]
    public double? AvrgNoElderlyHousehold { get; set; }

    [Column("Literatacy_Rate")]
    public double? LiteratacyRate { get; set; }

    [Column("Illiteratacy_Rate_Females")]
    public double? IlliteratacyRateFemales { get; set; }

    [Column("Education_10Years")]
    public double? Education10years { get; set; }

    [Column("Education_10Years_Females")]
    public double? Education10yearsFemales { get; set; }

    [Column("University_Education")]
    public double? UniversityEducation { get; set; }

    [Column("University_Education_Females")]
    public double? UniversityEducationFemales { get; set; }

    [Column("Not_enrolled_school_6to18years")]
    public double? NotEnrolledSchool6to18years { get; set; }

    [Column("Not_enrolled_school_6to18years_females")]
    public double? NotEnrolledSchool6to18yearsFemales { get; set; }

    [Column("Dropout_School_6to18yeares")]
    public double? DropoutSchool6to18yeares { get; set; }

    [Column("Dropout_School_6to18yeares_females")]
    public double? DropoutSchool6to18yearesFemales { get; set; }

    [Column("Participated_labor_force_15yeares")]
    public double? ParticipatedLaborForce15yeares { get; set; }

    [Column("Participated_labor_force_15yeares_females")]
    public double? ParticipatedLaborForce15yearesFemales { get; set; }

    [Column("Adult_Employed_from_labour_face_24yeares")]
    public double? AdultEmployedFromLabourFace24yeares { get; set; }

    [Column("Adult_employed")]
    public double? AdultEmployed { get; set; }

    [Column("Females_employed_from_total_Females_employed")]
    public double? FemalesEmployedFromTotalFemalesEmployed { get; set; }

    [Column("Adult_Unpaid_Employed")]
    public double? AdultUnpaidEmployed { get; set; }

    [Column("Unpaid_Employed_Females_from_total_employed_females")]
    public double? UnpaidEmployedFemalesFromTotalEmployedFemales { get; set; }

    [Column("Adult_wage_workers")]
    public double? AdultWageWorkers { get; set; }

    [Column("Adult_Females_wage_workers_from_total_employed_Females")]
    public double? AdultFemalesWageWorkersFromTotalEmployedFemales { get; set; }

    [Column("unemplyment_rate")]
    public double? UnemplymentRate { get; set; }

    [Column("Females_unemplyment_rate")]
    public double? FemalesUnemplymentRate { get; set; }

    [Column("Workers_agriculture")]
    public double? WorkersAgriculture { get; set; }

    [Column("females_Workers_agriculture_from_toyal_females_employed")]
    public double? FemalesWorkersAgricultureFromToyalFemalesEmployed { get; set; }

    [Column("Wage_Workers_agriculture")]
    public double? WageWorkersAgriculture { get; set; }

    [Column("Wage_females_Workers_agriculture")]
    public double? WageFemalesWorkersAgriculture { get; set; }

    [Column("Employed_working_outside_Establishment")]
    public double? EmployedWorkingOutsideEstablishment { get; set; }

    [Column("Employed_working_outside_Establishment1")]
    public double? EmployedWorkingOutsideEstablishment1 { get; set; }

    [Column("employed_working_government_public_sector")]
    public double? EmployedWorkingGovernmentPublicSector { get; set; }

    [Column("employed_working_government_private_sector")]
    public double? EmployedWorkingGovernmentPrivateSector { get; set; }

    [Column("employed_working_permanent_jobs")]
    public double? EmployedWorkingPermanentJobs { get; set; }

    [Column("employed_working_Temporary_jobs")]
    public double? EmployedWorkingTemporaryJobs { get; set; }

    [Column("employed_females_working_Temporary_jobs")]
    public double? EmployedFemalesWorkingTemporaryJobs { get; set; }

    [Column("Per_Individuals_living_apartment")]
    public double? PerIndividualsLivingApartment { get; set; }

    [Column("Per_Individuals_living_rural_house")]
    public double? PerIndividualsLivingRuralHouse { get; set; }

    [Column("Per_individuals_having_public_water_network")]
    public double? PerIndividualsHavingPublicWaterNetwork { get; set; }

    [Column("Per_individuals_having_tap_in_house")]
    public double? PerIndividualsHavingTapInHouse { get; set; }

    [Column("Per_individuals_using_electricity_lighting")]
    public double? PerIndividualsUsingElectricityLighting { get; set; }

    [Column("Per_individuals_having_public_sanitation_network")]
    public double? PerIndividualsHavingPublicSanitationNetwork { get; set; }

    [Column("Per_individuals_having_private_kitchen")]
    public double? PerIndividualsHavingPrivateKitchen { get; set; }

    [Column("Per_individuals_having_private_toilet")]
    public double? PerIndividualsHavingPrivateToilet { get; set; }

    [Column("Per_individuals_using_healthy_fuel")]
    public double? PerIndividualsUsingHealthyFuel { get; set; }

    [Column("Per_households_having_private_car")]
    public double? PerHouseholdsHavingPrivateCar { get; set; }

    [Column("households_having_TV")]
    public double? HouseholdsHavingTv { get; set; }

    [Column("Per_households_having_Refrigerator")]
    public double? PerHouseholdsHavingRefrigerator { get; set; }

    [Column("Per_households_having_personal_computer")]
    public double? PerHouseholdsHavingPersonalComputer { get; set; }

    [Column("Per_households_having_telephone_mobile")]
    public double? PerHouseholdsHavingTelephoneMobile { get; set; }

    [Column("Per_households_having_internet")]
    public double? PerHouseholdsHavingInternet { get; set; }
}