// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("GIS_qISM_MARKAZ_2006")]
public partial class GisQIsmMarkaz2006
{
    [Key]
    [Column("SEC_ID")]
    public int SecId { get; set; }

    [Column("SHAPE__ID")]
    public double? ShapeId { get; set; }

    [Column("GOV_ID")]
    public int? GovId { get; set; }

    [Column("SEC_NAME_A")]
    [StringLength(255)]
    public string SecNameA { get; set; }

    [Column("SEC_NAME_E")]
    [StringLength(255)]
    public string SecNameE { get; set; }

    [Required]
    [Column("SEC_CODE")]
    [StringLength(20)]
    public string SecCode { get; set; }

    [Column("SHAPE_Leng")]
    public double? ShapeLeng { get; set; }

    [Column("SHAPE_Area")]
    public double? ShapeArea { get; set; }

    [Column("lable_fld")]
    [StringLength(255)]
    public string LableFld { get; set; }

    [Column("illitracy")]
    public double? Illitracy { get; set; }

    [Column("poverty_pe")]
    public double? PovertyPe { get; set; }

    [Column("unemployme")]
    public double? Unemployme { get; set; }

    [Column("water_conn")]
    public double? WaterConn { get; set; }

    [Column("electric_c")]
    public double? ElectricC { get; set; }

    [Column("per_capeta")]
    public double? PerCapeta { get; set; }

    public int Id { get; set; }

    [InverseProperty("Sec")]
    public virtual ICollection<GisShyakhaVillage2006> GisShyakhaVillage2006s { get; set; } = new List<GisShyakhaVillage2006>();

    [ForeignKey("GovId")]
    [InverseProperty("GisQIsmMarkaz2006s")]
    public virtual GisGovernorates2006 Gov { get; set; }
}