// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("GIS_SHYAKHA_VILLAGE_N2006")]
public partial class GisShyakhaVillageN2006
{
    [Key]
    [Column("SSec_ID")]
    public int SsecId { get; set; }

    [Column("Sec_ID")]
    public int? SecId { get; set; }

    [Column("OBJECTID")]
    public int Objectid { get; set; }

    [Column(TypeName = "image")]
    public byte[] Shape { get; set; }

    [Column("SSEC_NAME_")]
    [StringLength(150)]
    public string SsecName { get; set; }

    [Column("SSEC_CODE")]
    [StringLength(6)]
    public string SsecCode { get; set; }

    [Column("SHAPE_Leng")]
    public double? ShapeLeng { get; set; }

    [Column("SHAPE_Le_1")]
    public double? ShapeLe1 { get; set; }

    [Column("SSEC_NAME1")]
    [StringLength(150)]
    public string SsecName1 { get; set; }

    [Column("Shape_Length")]
    public double? ShapeLength { get; set; }

    [Column("Shape_Area")]
    public double? ShapeArea { get; set; }

    [Column("poverty_pe")]
    public float? PovertyPe { get; set; }

    [Column("illitracy")]
    public float? Illitracy { get; set; }

    [Column("unemployme")]
    public float? Unemployme { get; set; }

    [Column("water_conn")]
    public float? WaterConn { get; set; }

    [Column("electric_c")]
    public float? ElectricC { get; set; }

    [Column("per_capeta")]
    public float? PerCapeta { get; set; }

    [Column("sanitation_conn")]
    public float? SanitationConn { get; set; }

    [Column("id_sec_4")]
    public short? IdSec4 { get; set; }

    [Column("id_sec_old")]
    public short? IdSecOld { get; set; }

    [ForeignKey("SecId")]
    [InverseProperty("GisShyakhaVillageN2006s")]
    public virtual GisQismMarkazN2006 Sec { get; set; }

    [InverseProperty("Ssec")]
    public virtual ICollection<TblApplicationOld> TblApplicationOlds { get; set; } = new List<TblApplicationOld>();
}