// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("GIS_SHYAKHA_VILLAGE")]
public partial class GisShyakhaVillage
{
    [Key]
    [Column("SSEC_ID")]
    public int SsecId { get; set; }

    [Column("SSEC_NAME_")]
    [StringLength(150)]
    public string SsecName { get; set; }

    [Column("SSEC_NAME1")]
    [StringLength(150)]
    public string SsecName1 { get; set; }

    [Column("SSEC_CODE")]
    [StringLength(6)]
    public string SsecCode { get; set; }
}