// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("GIS_water")]
public partial class GisWater
{
    [Column("OBJECTID_1")]
    public int Objectid1 { get; set; }

    [Column("NAME_A")]
    [StringLength(50)]
    public string NameA { get; set; }

    [Column("NAME_E")]
    [StringLength(50)]
    public string NameE { get; set; }
}