// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("History_Details")]
[Index("HcsId", Name = "IX_History_Details_HCS_ID")]
public partial class HistoryDetail
{
    [Key]
    [Column("HCA_ID")]
    public int HcaId { get; set; }

    [Column("HCS_ID")]
    public int? HcsId { get; set; }

    [Column("HCA_StatusAr")]
    [StringLength(150)]
    public string HcaStatusAr { get; set; }

    [Column("HCA_StatusEn")]
    [StringLength(150)]
    public string HcaStatusEn { get; set; }

    [Column("HCA_StatYear")]
    [StringLength(50)]
    public string HcaStatYear { get; set; }

    [Column("HCA_Image")]
    [StringLength(100)]
    public string HcaImage { get; set; }

    [Column("HCA_PDFAr")]
    [StringLength(250)]
    public string HcaPdfar { get; set; }

    [Column("HCA_PDFEn")]
    [StringLength(250)]
    public string HcaPdfen { get; set; }

    [Column("Per_ID")]
    public int? PerId { get; set; }

    [Column("HCA_HasGov")]
    public bool? HcaHasGov { get; set; }

    [Column("Gov_ID")]
    public int? GovId { get; set; }

    [Column("Year_ID")]
    public int? YearId { get; set; }

    [Column("Month_ID")]
    public int? MonthId { get; set; }

    [Column("Qua_ID")]
    public int? QuaId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("Status_Order")]
    public int? StatusOrder { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("HistoryDetailEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("HistoryDetailEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("GovId")]
    [InverseProperty("HistoryDetails")]
    public virtual TblGovernorate Gov { get; set; }

    [ForeignKey("HcsId")]
    [InverseProperty("HistoryDetails")]
    public virtual HistoryCategorySub Hcs { get; set; }

    [ForeignKey("MonthId")]
    [InverseProperty("HistoryDetails")]
    public virtual TblMonth Month { get; set; }

    [ForeignKey("PerId")]
    [InverseProperty("HistoryDetails")]
    public virtual TblPeriod Per { get; set; }

    [ForeignKey("QuaId")]
    [InverseProperty("HistoryDetails")]
    public virtual TblQuarter Qua { get; set; }

    [InverseProperty("Hca")]
    public virtual ICollection<TblStatistcalBulltinsYear> TblStatistcalBulltinsYears { get; set; } = new List<TblStatistcalBulltinsYear>();

    [ForeignKey("YearId")]
    [InverseProperty("HistoryDetails")]
    public virtual TblYear Year { get; set; }
}