// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("History_CategorySub")]
public partial class HistoryCategorySub
{
    [Key]
    [Column("HCS_ID")]
    public int HcsId { get; set; }

    [Column("SD_ID")]
    public int? SdId { get; set; }

    [Column("HC_ID")]
    public int? HcId { get; set; }

    [Column("HCS_NameAr")]
    public string HcsNameAr { get; set; }

    [Column("HCS_NameEn")]
    public string HcsNameEn { get; set; }

    [Column("HCS_InfoAr")]
    public string HcsInfoAr { get; set; }

    [Column("HCS_InfoEn")]
    public string HcsInfoEn { get; set; }

    [Column("cat_sub")]
    public int? CatSub { get; set; }

    [Column("catgroup")]
    public int? Catgroup { get; set; }

    [ForeignKey("HcId")]
    [InverseProperty("HistoryCategorySubs")]
    public virtual HistoryCategory Hc { get; set; }

    [InverseProperty("Hcs")]
    public virtual ICollection<HistoryDetail> HistoryDetails { get; set; } = new List<HistoryDetail>();

    [ForeignKey("SdId")]
    [InverseProperty("HistoryCategorySubs")]
    public virtual TblStatisticsDepartement Sd { get; set; }
}