// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("History_Categories")]
public partial class HistoryCategory
{
    [Key]
    [Column("HC_ID")]
    public int HcId { get; set; }

    [Column("HC_NameAr")]
    [StringLength(100)]
    public string HcNameAr { get; set; }

    [Column("HC_NameEn")]
    [StringLength(100)]
    public string HcNameEn { get; set; }

    [Column("MSM_ID")]
    public int? MsmId { get; set; }

    [Column("HC_Order")]
    public int? HcOrder { get; set; }

    [InverseProperty("Hc")]
    public virtual ICollection<HistoryCategorySub> HistoryCategorySubs { get; set; } = new List<HistoryCategorySub>();

    [ForeignKey("MsmId")]
    [InverseProperty("HistoryCategories")]
    public virtual TblMainSubMenu Msm { get; set; }
}