// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

public partial class IndicatorsUser
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(50)]
    public string TokenKey { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<IndicatorsUsersPriviliage> IndicatorsUsersPriviliages { get; set; } = new List<IndicatorsUsersPriviliage>();
}