// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("IndicatorRAndDDrow")]
public partial class IndicatorRandDdrow
{
    [Column("ind_ID")]
    public int? IndId { get; set; }

    [Column("ind_Name")]
    public string IndName { get; set; }

    [Column("decimal_No")]
    public string DecimalNo { get; set; }

    [Column("Ind_Scale")]
    public string IndScale { get; set; }

    [Column("Ind_YaxisName")]
    public string IndYaxisName { get; set; }

    [Column("IndData_ChartType_gen")]
    public string IndDataChartTypeGen { get; set; }

    [Column("IndData_ChartType_Urban")]
    public string IndDataChartTypeUrban { get; set; }

    [Column("IndData_ChartType_GeoArea")]
    public string IndDataChartTypeGeoArea { get; set; }

    [Column("IndData_ChartType_GenSector")]
    public string IndDataChartTypeGenSector { get; set; }

    [Column("IndData_ChartType_CountrySector")]
    public string IndDataChartTypeCountrySector { get; set; }

    [Column("IndData_ChartType_LegalEntity")]
    public string IndDataChartTypeLegalEntity { get; set; }

    [Column("IndData_ChartType_Activity")]
    public string IndDataChartTypeActivity { get; set; }

    [Column("IndData_Category_name_1")]
    public string IndDataCategoryName1 { get; set; }

    [Column("IndData_ChartType_OtherData1")]
    public string IndDataChartTypeOtherData1 { get; set; }

    [Column("IndData_Category_name_2")]
    public string IndDataCategoryName2 { get; set; }

    [Column("IndData_ChartType_OtherData2")]
    public string IndDataChartTypeOtherData2 { get; set; }

    [Column("IndData_Category_name_3")]
    public string IndDataCategoryName3 { get; set; }

    [Column("IndData_ChartType_OtherData3")]
    public string IndDataChartTypeOtherData3 { get; set; }

    [Column("IndData_Category_name_4")]
    public string IndDataCategoryName4 { get; set; }

    [Column("IndData_ChartType_OtherData4")]
    public string IndDataChartTypeOtherData4 { get; set; }

    [Column("IndData_Category_name_5")]
    public string IndDataCategoryName5 { get; set; }

    [Column("IndData_ChartType_OtherData5")]
    public string IndDataChartTypeOtherData5 { get; set; }

    [Column("IndData_Category_name_6")]
    public string IndDataCategoryName6 { get; set; }

    [Column("IndData_ChartType_OtherData6")]
    public string IndDataChartTypeOtherData6 { get; set; }

    [Column("IndData_Category_name_7")]
    public string IndDataCategoryName7 { get; set; }

    [Column("IndData_ChartType_OtherData7")]
    public string IndDataChartTypeOtherData7 { get; set; }

    [Column("IndData_Category_name_8")]
    public string IndDataCategoryName8 { get; set; }

    [Column("IndData_ChartType_OtherData8")]
    public string IndDataChartTypeOtherData8 { get; set; }
}