// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("Lobna_2")]
public partial class Lobna2
{
    [Column("f1")]
    [StringLength(1000)]
    public string F1 { get; set; }

    [Column("f2")]
    [StringLength(2000)]
    public string F2 { get; set; }

    [Column("f3")]
    [StringLength(100)]
    public string F3 { get; set; }

    [Column("f4")]
    [StringLength(100)]
    public string F4 { get; set; }

    [Column("f5")]
    [StringLength(100)]
    public string F5 { get; set; }

    [Column("f6")]
    [StringLength(100)]
    public string F6 { get; set; }
}