// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("Question_Link")]
public partial class QuestionLink
{
    [Key]
    [Column("QL_ID")]
    public int QlId { get; set; }

    [Column("QL_Link")]
    [StringLength(150)]
    public string QlLink { get; set; }

    [Column("QL_Name")]
    [StringLength(150)]
    public string QlName { get; set; }

    [Column("Que_ID")]
    public int? QueId { get; set; }

    [ForeignKey("QueId")]
    [InverseProperty("QuestionLinks")]
    public virtual TblQuestion Que { get; set; }
}