// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("research")]
public partial class Research
{
    [StringLength(255)]
    public string F1 { get; set; }

    [StringLength(255)]
    public string F2 { get; set; }

    [StringLength(255)]
    public string F3 { get; set; }

    [StringLength(50)]
    public string F4 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? F5 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? F6 { get; set; }
}