// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
public partial class RestrictedBullitin
{
    [Column("SB_ID")]
    public int SbId { get; set; }

    [Column("SD_ID")]
    public int? SdId { get; set; }

    [Required]
    [Column("SB_ArNAme")]
    [StringLength(250)]
    public string SbArName { get; set; }

    [Required]
    [Column("SB_EnName")]
    [StringLength(250)]
    public string SbEnName { get; set; }

    [Required]
    [Column("SB_BriefAr")]
    public string SbBriefAr { get; set; }

    [Column("SB_BriefEn")]
    public string SbBriefEn { get; set; }

    [Column("SB_CreatedDate", TypeName = "datetime")]
    public DateTime? SbCreatedDate { get; set; }

    [Required]
    [Column("SB_MainTopicsAr")]
    public string SbMainTopicsAr { get; set; }

    [Column("SB_MainTopicsEn")]
    public string SbMainTopicsEn { get; set; }

    [Column("SB_Visible")]
    public bool? SbVisible { get; set; }

    [Column("Per_ID")]
    public int PerId { get; set; }

    [Column("SB_Restricted")]
    public bool? SbRestricted { get; set; }

    [Column("SB_Link")]
    [StringLength(150)]
    public string SbLink { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("SC_ID")]
    public int? ScId { get; set; }

    [Column("Man_ID")]
    public int? ManId { get; set; }

    [Column("MSM_ID")]
    public int? MsmId { get; set; }

    [Column("PubT_ID")]
    public int? PubTId { get; set; }

    [Column("SB_Cat")]
    public int? SbCat { get; set; }
}