// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblAudio")]
public partial class TblAudio
{
    [Key]
    [Column("Audio_Id")]
    public int AudioId { get; set; }

    [Column("Audio_Path")]
    [StringLength(250)]
    public string AudioPath { get; set; }

    [Column("Audio_visible")]
    public bool? AudioVisible { get; set; }

    [Column("Audio_Date", TypeName = "datetime")]
    public DateTime? AudioDate { get; set; }

    [Column("Audio_Active")]
    public bool? AudioActive { get; set; }

    [Column("SI_ID")]
    public int? SiId { get; set; }

    [Column("Audio_NameAr")]
    [StringLength(150)]
    public string AudioNameAr { get; set; }

    [Column("Audion_NameEn")]
    [StringLength(150)]
    public string AudionNameEn { get; set; }

    [ForeignKey("SiId")]
    [InverseProperty("TblAudios")]
    public virtual TblSemanticIssue Si { get; set; }
}