// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblApplication_Users")]
public partial class TblApplicationUser
{
    [Key]
    [Column("AppUsr_ID")]
    public int AppUsrId { get; set; }

    [Column("AppUsr_UserName")]
    [StringLength(20)]
    public string AppUsrUserName { get; set; }

    [Column("AppUsr_Password")]
    [StringLength(50)]
    public string AppUsrPassword { get; set; }

    [Column("AppUsr_OfficeNo")]
    [StringLength(3)]
    public string AppUsrOfficeNo { get; set; }

    [Column("AppUsr_OfficeTelephone")]
    [StringLength(250)]
    public string AppUsrOfficeTelephone { get; set; }

    [Column("AppUsr_OfficeName")]
    [StringLength(50)]
    public string AppUsrOfficeName { get; set; }

    [Column("AppUsr_OfficeAddress")]
    [StringLength(250)]
    public string AppUsrOfficeAddress { get; set; }

    [Column("Gov_ID")]
    public int? GovId { get; set; }

    [ForeignKey("GovId")]
    [InverseProperty("TblApplicationUsers")]
    public virtual GisGovernorates2006 Gov { get; set; }

    [InverseProperty("AppUsr")]
    public virtual ICollection<TblApplicationOld> TblApplicationOlds { get; set; } = new List<TblApplicationOld>();
}