// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblCentres")]
public partial class TblCentre
{
    [Key]
    [Column("centre_ID")]
    public int CentreId { get; set; }

    [Column("Centre_NameAr")]
    [StringLength(50)]
    public string CentreNameAr { get; set; }

    [Column("Centre_NameEn")]
    [StringLength(50)]
    public string CentreNameEn { get; set; }

    [Column("Centre_Code")]
    [StringLength(20)]
    public string CentreCode { get; set; }

    [Column("Gov_ID")]
    public int? GovId { get; set; }

    [ForeignKey("GovId")]
    [InverseProperty("TblCentres")]
    public virtual TblGovernorate Gov { get; set; }
}