// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblCompanies")]
public partial class TblCompany
{
    [Key]
    [Column("Com_ID")]
    public int ComId { get; set; }

    [Column("Com_NameAr")]
    [StringLength(100)]
    public string ComNameAr { get; set; }

    [Column("Com_NameEn")]
    [StringLength(100)]
    public string ComNameEn { get; set; }

    [Column("Com_TaxNo")]
    [StringLength(50)]
    public string ComTaxNo { get; set; }

    [Column("Com_FileNo")]
    [StringLength(50)]
    public string ComFileNo { get; set; }

    [Column("Com_Activate")]
    public bool? ComActivate { get; set; }

    [InverseProperty("Com")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}