// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblClock2")]
public partial class TblClock2
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    public long? ClockNumber { get; set; }
}