// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblCAPMASMangements")]
public partial class TblCapmasmangement
{
    [Key]
    [Column("Man_ID")]
    public int ManId { get; set; }

    [Column("GenMag_Name")]
    [StringLength(50)]
    public string GenMagName { get; set; }

    [Column("GenMag_Name_EN")]
    [StringLength(50)]
    public string GenMagNameEn { get; set; }

    [Column("CCM_ID")]
    public int? CcmId { get; set; }

    [ForeignKey("CcmId")]
    [InverseProperty("TblCapmasmangements")]
    public virtual TblCapmasCentralManagment Ccm { get; set; }

    [InverseProperty("Man")]
    public virtual ICollection<TblPosition> TblPositions { get; set; } = new List<TblPosition>();

    [InverseProperty("Man")]
    public virtual ICollection<TblQuestion> TblQuestions { get; set; } = new List<TblQuestion>();

    [InverseProperty("Man")]
    public virtual ICollection<TblStatisticsBulltin> TblStatisticsBulltins { get; set; } = new List<TblStatisticsBulltin>();
}