// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblEmployees")]
public partial class TblEmployee
{
    [Key]
    [Column("Emp_ID")]
    public int EmpId { get; set; }

    [Column("Emp_Name")]
    [StringLength(100)]
    public string EmpName { get; set; }

    [Column("Emp_Password")]
    [StringLength(50)]
    public string EmpPassword { get; set; }

    [Column("Pos_ID")]
    public int PosId { get; set; }

    [Column("EmpGr_ID")]
    public int? EmpGrId { get; set; }

    [ForeignKey("EmpGrId")]
    [InverseProperty("TblEmployees")]
    public virtual TblEmployeesGroup EmpGr { get; set; }

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<HistoryDetail> HistoryDetailEmpCreateNavigations { get; set; } = new List<HistoryDetail>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<HistoryDetail> HistoryDetailEmpLastUpdateNavigations { get; set; } = new List<HistoryDetail>();

    [ForeignKey("PosId")]
    [InverseProperty("TblEmployees")]
    public virtual TblPosition Pos { get; set; }

    [InverseProperty("Emp")]
    public virtual ICollection<TblDisscutionTopic> TblDisscutionTopics { get; set; } = new List<TblDisscutionTopic>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblEducationCategory> TblEducationCategoryEmpCreateNavigations { get; set; } = new List<TblEducationCategory>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblEducationCategory> TblEducationCategoryEmpLastUpdateNavigations { get; set; } = new List<TblEducationCategory>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblMainMenu> TblMainMenuEmpCreateNavigations { get; set; } = new List<TblMainMenu>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblMainMenu> TblMainMenuEmpLastUpdateNavigations { get; set; } = new List<TblMainMenu>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblMainPagesSector> TblMainPagesSectorEmpCreateNavigations { get; set; } = new List<TblMainPagesSector>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblMainPagesSector> TblMainPagesSectorEmpLastUpdateNavigations { get; set; } = new List<TblMainPagesSector>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblMainPublication> TblMainPublicationEmpCreateNavigations { get; set; } = new List<TblMainPublication>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblMainPublication> TblMainPublicationEmpLastUpdateNavigations { get; set; } = new List<TblMainPublication>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblMainSubMenu> TblMainSubMenuEmpCreateNavigations { get; set; } = new List<TblMainSubMenu>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblMainSubMenu> TblMainSubMenuEmpLastUpdateNavigations { get; set; } = new List<TblMainSubMenu>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblNewsFile> TblNewsFileEmpCreateNavigations { get; set; } = new List<TblNewsFile>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblNewsFile> TblNewsFileEmpLastUpdateNavigations { get; set; } = new List<TblNewsFile>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblNewsType> TblNewsTypeEmpCreateNavigations { get; set; } = new List<TblNewsType>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblNewsType> TblNewsTypeEmpLastUpdateNavigations { get; set; } = new List<TblNewsType>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblNewsTypesMainSubMenu> TblNewsTypesMainSubMenuEmpCreateNavigations { get; set; } = new List<TblNewsTypesMainSubMenu>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblNewsTypesMainSubMenu> TblNewsTypesMainSubMenuEmpLastUpdateNavigations { get; set; } = new List<TblNewsTypesMainSubMenu>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblPage> TblPageEmpCreateNavigations { get; set; } = new List<TblPage>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblPage> TblPageEmpLastUpdateNavigations { get; set; } = new List<TblPage>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblPagesSector> TblPagesSectorEmpCreateNavigations { get; set; } = new List<TblPagesSector>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblPagesSector> TblPagesSectorEmpLastUpdateNavigations { get; set; } = new List<TblPagesSector>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblPaperCategory> TblPaperCategoryEmpCreateNavigations { get; set; } = new List<TblPaperCategory>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblPaperCategory> TblPaperCategoryEmpLastUpdateNavigations { get; set; } = new List<TblPaperCategory>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblPaper> TblPaperEmpCreateNavigations { get; set; } = new List<TblPaper>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblPaper> TblPaperEmpLastUpdateNavigations { get; set; } = new List<TblPaper>();

    [InverseProperty("Emp")]
    public virtual ICollection<TblPaper> TblPaperEmps { get; set; } = new List<TblPaper>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblRequestCategory> TblRequestCategoryEmpCreateNavigations { get; set; } = new List<TblRequestCategory>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblRequestCategory> TblRequestCategoryEmpLastUpdateNavigations { get; set; } = new List<TblRequestCategory>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblRequest> TblRequestEmpCreateNavigations { get; set; } = new List<TblRequest>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblRequest> TblRequestEmpLastUpdateNavigations { get; set; } = new List<TblRequest>();

    [InverseProperty("Emp")]
    public virtual ICollection<TblRequestRegisteration> TblRequestRegisterations { get; set; } = new List<TblRequestRegisteration>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblReseachAndFormsCategory> TblReseachAndFormsCategoryEmpCreateNavigations { get; set; } = new List<TblReseachAndFormsCategory>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblReseachAndFormsCategory> TblReseachAndFormsCategoryEmpLastUpdateNavigations { get; set; } = new List<TblReseachAndFormsCategory>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblResearchLink> TblResearchLinkEmpCreateNavigations { get; set; } = new List<TblResearchLink>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblResearchLink> TblResearchLinkEmpLastUpdateNavigations { get; set; } = new List<TblResearchLink>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblResearchsAndForm> TblResearchsAndFormEmpCreateNavigations { get; set; } = new List<TblResearchsAndForm>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblResearchsAndForm> TblResearchsAndFormEmpLastUpdateNavigations { get; set; } = new List<TblResearchsAndForm>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblReserchesAndFormsYear> TblReserchesAndFormsYearEmpCreateNavigations { get; set; } = new List<TblReserchesAndFormsYear>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblReserchesAndFormsYear> TblReserchesAndFormsYearEmpLastUpdateNavigations { get; set; } = new List<TblReserchesAndFormsYear>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblSiteCategory> TblSiteCategoryEmpCreateNavigations { get; set; } = new List<TblSiteCategory>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblSiteCategory> TblSiteCategoryEmpLastUpdateNavigations { get; set; } = new List<TblSiteCategory>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblSite> TblSiteEmpCreateNavigations { get; set; } = new List<TblSite>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblSite> TblSiteEmpLastUpdateNavigations { get; set; } = new List<TblSite>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblStatistcalBulltinsYear> TblStatistcalBulltinsYearEmpCreateNavigations { get; set; } = new List<TblStatistcalBulltinsYear>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblStatistcalBulltinsYear> TblStatistcalBulltinsYearEmpLastUpdateNavigations { get; set; } = new List<TblStatistcalBulltinsYear>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblStatisticsBulltin> TblStatisticsBulltinEmpCreateNavigations { get; set; } = new List<TblStatisticsBulltin>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblStatisticsBulltin> TblStatisticsBulltinEmpLastUpdateNavigations { get; set; } = new List<TblStatisticsBulltin>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblStatisticsBulltinsSector> TblStatisticsBulltinsSectorEmpCreateNavigations { get; set; } = new List<TblStatisticsBulltinsSector>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblStatisticsBulltinsSector> TblStatisticsBulltinsSectorEmpLastUpdateNavigations { get; set; } = new List<TblStatisticsBulltinsSector>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblStatisticsBulltinsSectoreDatum> TblStatisticsBulltinsSectoreDatumEmpCreateNavigations { get; set; } = new List<TblStatisticsBulltinsSectoreDatum>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblStatisticsBulltinsSectoreDatum> TblStatisticsBulltinsSectoreDatumEmpLastUpdateNavigations { get; set; } = new List<TblStatisticsBulltinsSectoreDatum>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblStatisticsDepartement> TblStatisticsDepartementEmpCreateNavigations { get; set; } = new List<TblStatisticsDepartement>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblStatisticsDepartement> TblStatisticsDepartementEmpLastUpdateNavigations { get; set; } = new List<TblStatisticsDepartement>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblUser> TblUserEmpCreateNavigations { get; set; } = new List<TblUser>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblUser> TblUserEmpLastUpdateNavigations { get; set; } = new List<TblUser>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblUserGroup> TblUserGroupEmpCreateNavigations { get; set; } = new List<TblUserGroup>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblUserGroup> TblUserGroupEmpLastUpdateNavigations { get; set; } = new List<TblUserGroup>();

    [InverseProperty("Emp")]
    public virtual ICollection<TblUsersAnswer> TblUsersAnswers { get; set; } = new List<TblUsersAnswer>();

    [InverseProperty("EmpCreateNavigation")]
    public virtual ICollection<TblUsersGroupsBulltin> TblUsersGroupsBulltinEmpCreateNavigations { get; set; } = new List<TblUsersGroupsBulltin>();

    [InverseProperty("EmpLastUpdateNavigation")]
    public virtual ICollection<TblUsersGroupsBulltin> TblUsersGroupsBulltinEmpLastUpdateNavigations { get; set; } = new List<TblUsersGroupsBulltin>();
}