// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblEducationCategory")]
public partial class TblEducationCategory
{
    [Key]
    [Column("EC_ID")]
    public int EcId { get; set; }

    [Column("EC_NameAr")]
    [StringLength(100)]
    public string EcNameAr { get; set; }

    [Column("EC_NameEn")]
    [StringLength(100)]
    public string EcNameEn { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblEducationCategoryEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblEducationCategoryEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [InverseProperty("Ec")]
    public virtual ICollection<TblRequestRegisteration> TblRequestRegisterations { get; set; } = new List<TblRequestRegisteration>();
}