// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblEmployeesGroup")]
public partial class TblEmployeesGroup
{
    [Key]
    [Column("EmpGr_ID")]
    public int EmpGrId { get; set; }

    [Column("EmpGr_NameAr")]
    [StringLength(50)]
    public string EmpGrNameAr { get; set; }

    [Column("EmpGr_NameEn")]
    [StringLength(50)]
    public string EmpGrNameEn { get; set; }

    [InverseProperty("EmpGr")]
    public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();

    [InverseProperty("EmpGr")]
    public virtual ICollection<TblPermission> TblPermissions { get; set; } = new List<TblPermission>();
}