// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblElectoronicSurvey")]
public partial class TblElectoronicSurvey
{
    [Key]
    [Column("ES_ID")]
    public int EsId { get; set; }

    [Column("ES_NameAr")]
    [StringLength(100)]
    public string EsNameAr { get; set; }

    [Column("ES_NameEn")]
    [StringLength(100)]
    public string EsNameEn { get; set; }

    [Column("ES_DescAr", TypeName = "text")]
    public string EsDescAr { get; set; }

    [Column("ES_DescEn", TypeName = "text")]
    public string EsDescEn { get; set; }

    [Column("ES_URL")]
    [StringLength(150)]
    public string EsUrl { get; set; }
}