// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblFAQ")]
public partial class TblFaq
{
    [Key]
    [Column("FAQ_ID")]
    public int FaqId { get; set; }

    [Column("FAQ_QuestionAr", TypeName = "text")]
    public string FaqQuestionAr { get; set; }

    [Column("FAQ_AnswerAr", TypeName = "text")]
    public string FaqAnswerAr { get; set; }

    [Column("FAQ_QuestionEn", TypeName = "text")]
    public string FaqQuestionEn { get; set; }

    [Column("FAQ_AnswerEn", TypeName = "text")]
    public string FaqAnswerEn { get; set; }

    [Column("SD_ID")]
    public int? SdId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("SdId")]
    [InverseProperty("TblFaqs")]
    public virtual TblStatisticsDepartement Sd { get; set; }
}