// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblFormGroups")]
public partial class TblFormGroup
{
    [Key]
    [Column("FG_ID")]
    public int FgId { get; set; }

    [Column("FG_NameAr")]
    [StringLength(200)]
    public string FgNameAr { get; set; }

    [Column("FG_NameEn")]
    [StringLength(200)]
    public string FgNameEn { get; set; }

    [Column("FC_ID")]
    public int? FcId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("FcId")]
    [InverseProperty("TblFormGroups")]
    public virtual TblFormCategory Fc { get; set; }

    [InverseProperty("Fg")]
    public virtual ICollection<TblForm> TblForms { get; set; } = new List<TblForm>();
}