// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblFoundation")]
public partial class TblFoundation
{
    [Key]
    [Column("Fo_ID")]
    public int FoId { get; set; }

    [Column("Fo_NameAr")]
    [StringLength(50)]
    public string FoNameAr { get; set; }

    [Column("Fo_NameEn")]
    [StringLength(50)]
    public string FoNameEn { get; set; }

    [InverseProperty("Fo")]
    public virtual ICollection<TblResearchesAgreement> TblResearchesAgreements { get; set; } = new List<TblResearchesAgreement>();
}