// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblForms")]
public partial class TblForm
{
    [Key]
    [Column("Forms_ID")]
    public int FormsId { get; set; }

    [Column("Forms_NameAr")]
    [StringLength(200)]
    public string FormsNameAr { get; set; }

    [Column("Forms_NameEn")]
    [StringLength(200)]
    public string FormsNameEn { get; set; }

    [Column("Forms_LinkAr")]
    [StringLength(200)]
    public string FormsLinkAr { get; set; }

    [Column("Forms_LinkEn")]
    [StringLength(200)]
    public string FormsLinkEn { get; set; }

    [Column("Forms_LastUpdate")]
    [StringLength(20)]
    public string FormsLastUpdate { get; set; }

    [Column("FG_ID")]
    public int? FgId { get; set; }

    [ForeignKey("FgId")]
    [InverseProperty("TblForms")]
    public virtual TblFormGroup Fg { get; set; }
}