// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblGovernorates")]
public partial class TblGovernorate
{
    [Key]
    [Column("Gov_ID")]
    public int GovId { get; set; }

    [Column("Gov_NameAr")]
    [StringLength(150)]
    public string GovNameAr { get; set; }

    [Column("Gov_NameEn")]
    [StringLength(150)]
    public string GovNameEn { get; set; }

    [Column("Gov_Order")]
    public int? GovOrder { get; set; }

    [Column("Gov_Code")]
    [StringLength(2)]
    public string GovCode { get; set; }

    [Column("id")]
    public int? Id { get; set; }

    [InverseProperty("Gov")]
    public virtual ICollection<HistoryDetail> HistoryDetails { get; set; } = new List<HistoryDetail>();

    [InverseProperty("Gov")]
    public virtual ICollection<TblCentre> TblCentres { get; set; } = new List<TblCentre>();

    [InverseProperty("Gov")]
    public virtual ICollection<TblPopulationClock> TblPopulationClocks { get; set; } = new List<TblPopulationClock>();
}