// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("tblIndicators_translate2")]
public partial class TblIndicatorsTranslate2
{
    [Column("Ind_ID")]
    public int? IndId { get; set; }

    [Column("Ind_NameAr")]
    public string IndNameAr { get; set; }

    [Column("Ind_NameEn")]
    public string IndNameEn { get; set; }

    [Column("Ind_DescAr", TypeName = "text")]
    public string IndDescAr { get; set; }

    [Column("Ind_DescEn", TypeName = "text")]
    public string IndDescEn { get; set; }

    [Column("Ind_IdentifyAr")]
    public string IndIdentifyAr { get; set; }

    [Column("Ind_IdentifyEn")]
    public string IndIdentifyEn { get; set; }

    [Column("Ind_CalcMethodAr")]
    public string IndCalcMethodAr { get; set; }

    [Column("Ind_CalcMethodEn")]
    public string IndCalcMethodEn { get; set; }

    [Column("Ind_DataSourceAr")]
    public string IndDataSourceAr { get; set; }

    [Column("Ind_DataSourceEn")]
    public string IndDataSourceEn { get; set; }

    [Column("Ind_MethodologyAr")]
    public string IndMethodologyAr { get; set; }

    [Column("Ind_MethodologyEn")]
    public string IndMethodologyEn { get; set; }

    [Column("Ind_YaxisName")]
    [StringLength(100)]
    public string IndYaxisName { get; set; }

    [Column("Ind_YaxisName_En")]
    [StringLength(100)]
    public string IndYaxisNameEn { get; set; }
}