// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblImportantIndicators")]
public partial class TblImportantIndicator
{
    [Key]
    [Column("ImpInd_ID")]
    public int ImpIndId { get; set; }

    [Column("Ind_ID")]
    public int? IndId { get; set; }

    [Column("IndData_ID")]
    public int? IndDataId { get; set; }

    [Column("ImpInd_Title")]
    [StringLength(50)]
    public string ImpIndTitle { get; set; }

    [Column("ImpInd_Title_En")]
    [StringLength(50)]
    public string ImpIndTitleEn { get; set; }

    [Column("ImpInd_PriefDesc")]
    [StringLength(150)]
    public string ImpIndPriefDesc { get; set; }

    [Column("ImpInd_PriefDesc_En")]
    [StringLength(150)]
    public string ImpIndPriefDescEn { get; set; }

    [Column("ImpInd_Arrow")]
    public bool? ImpIndArrow { get; set; }

    [Column("ImpInd_ArrowUpDirection")]
    public bool? ImpIndArrowUpDirection { get; set; }

    [Column("ImpInd_ArrowDownDirection")]
    public bool? ImpIndArrowDownDirection { get; set; }

    [Column("ImpInd_RedColor")]
    public bool? ImpIndRedColor { get; set; }

    [Column("ImpInd_GreenColor")]
    public bool? ImpIndGreenColor { get; set; }

    [Column("ImpInd_PublishedDate", TypeName = "datetime")]
    public DateTime? ImpIndPublishedDate { get; set; }

    [Column("ImpInd_Visable")]
    public bool? ImpIndVisable { get; set; }

    [Column("ImpInd_Closed")]
    public bool? ImpIndClosed { get; set; }

    [Column("Internal_Show")]
    public bool? InternalShow { get; set; }

    [Column("ImpInd_DateofShow", TypeName = "datetime")]
    public DateTime? ImpIndDateofShow { get; set; }

    [Column("ImpInd_PeriodofShow")]
    public int? ImpIndPeriodofShow { get; set; }

    [ForeignKey("IndId")]
    [InverseProperty("TblImportantIndicators")]
    public virtual TblIndicator Ind { get; set; }

    [ForeignKey("IndDataId")]
    [InverseProperty("TblImportantIndicators")]
    public virtual TblIndicatorDatum IndData { get; set; }
}