// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblImpPubLink")]
public partial class TblImpPubLink
{
    [Key]
    [Column("ImPL_ID")]
    public int ImPlId { get; set; }

    [Column("ImPL_NameAr")]
    [StringLength(100)]
    public string ImPlNameAr { get; set; }

    [Column("ImPL_NameEn")]
    [StringLength(100)]
    public string ImPlNameEn { get; set; }

    [Column("ImPL_LinkAr")]
    [StringLength(150)]
    public string ImPlLinkAr { get; set; }

    [Column("ImPL_LinkEn")]
    [StringLength(150)]
    public string ImPlLinkEn { get; set; }

    [Column("ImpPub_ID")]
    public int? ImpPubId { get; set; }

    [Column("ImPL_Visible")]
    public bool? ImPlVisible { get; set; }

    [ForeignKey("ImpPubId")]
    [InverseProperty("TblImpPubLinks")]
    public virtual TblImpPub ImpPub { get; set; }
}