// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblIndicatorCountrySectors")]
public partial class TblIndicatorCountrySector
{
    [Key]
    [Column("CountrySectors_ID")]
    public int CountrySectorsId { get; set; }

    [Column("CountrySectors_NameAr")]
    [StringLength(40)]
    public string CountrySectorsNameAr { get; set; }

    [Column("CountrySectors_NameEn")]
    [StringLength(40)]
    public string CountrySectorsNameEn { get; set; }
}