// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblImpPub")]
public partial class TblImpPub
{
    [Key]
    [Column("ImpPub_ID")]
    public int ImpPubId { get; set; }

    [Column("ImpPub_NameAr")]
    [StringLength(100)]
    public string ImpPubNameAr { get; set; }

    [Column("ImpPub_NameEn")]
    [StringLength(100)]
    public string ImpPubNameEn { get; set; }

    [Column("ImpPub_DescAr")]
    [StringLength(300)]
    public string ImpPubDescAr { get; set; }

    [Column("ImpPub_DescEn")]
    [StringLength(300)]
    public string ImpPubDescEn { get; set; }

    [Column("ImpPub_ImgLink")]
    [StringLength(150)]
    public string ImpPubImgLink { get; set; }

    [Column("ImpPub_PdfLinkAr")]
    [StringLength(150)]
    public string ImpPubPdfLinkAr { get; set; }

    [Column("ImpPub_PdfLinkEn")]
    [StringLength(150)]
    public string ImpPubPdfLinkEn { get; set; }

    [Column("ImpPub_Visible")]
    public bool? ImpPubVisible { get; set; }

    [InverseProperty("ImpPub")]
    public virtual ICollection<TblImpPubLink> TblImpPubLinks { get; set; } = new List<TblImpPubLink>();
}