// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblInternationalIndicators")]
public partial class TblInternationalIndicator
{
    [Key]
    [Column("IntInd_ID")]
    public int IntIndId { get; set; }

    [Column("IntInd_NameAr")]
    [StringLength(100)]
    public string IntIndNameAr { get; set; }

    [Column("IntInd_NameEn")]
    [StringLength(100)]
    public string IntIndNameEn { get; set; }

    [Column("IntInd_DescAr")]
    [StringLength(150)]
    public string IntIndDescAr { get; set; }

    [Column("IntInd_DescEn")]
    [StringLength(150)]
    public string IntIndDescEn { get; set; }

    [Column("IntInd_Visable")]
    public bool? IntIndVisable { get; set; }

    [Column("IntInd_VisableInMain")]
    public bool? IntIndVisableInMain { get; set; }

    [Column("Internal_Show")]
    public bool? InternalShow { get; set; }

    [InverseProperty("IntInd")]
    public virtual ICollection<TblInternationalIndicatorsDetail> TblInternationalIndicatorsDetails { get; set; } = new List<TblInternationalIndicatorsDetail>();
}