// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblIndicators_MainShow")]
public partial class TblIndicatorsMainShow
{
    [Key]
    [Column("IndM_ID")]
    public int IndMId { get; set; }

    [Column("Ind_ID")]
    public int? IndId { get; set; }

    [Column("IndData_ID")]
    public int? IndDataId { get; set; }

    [Column("IndM_Level")]
    public int? IndMLevel { get; set; }

    [Column("IndM_Sort")]
    public int? IndMSort { get; set; }

    [Column("IndM_Visable")]
    public bool? IndMVisable { get; set; }

    [Column("IndM_Closed")]
    public bool? IndMClosed { get; set; }

    [Column("IndM_PublishedDate", TypeName = "datetime")]
    public DateTime? IndMPublishedDate { get; set; }

    [Column("IndM_Name")]
    [StringLength(60)]
    public string IndMName { get; set; }

    [Column("IndM_Name_En")]
    [StringLength(60)]
    public string IndMNameEn { get; set; }

    [Column("IndM_ImagePath")]
    [StringLength(250)]
    public string IndMImagePath { get; set; }

    [Column("IndM_Date")]
    [StringLength(50)]
    public string IndMDate { get; set; }

    [Column("Internal_Show")]
    public bool? InternalShow { get; set; }

    [Column("IndM_DateofShow", TypeName = "datetime")]
    public DateTime? IndMDateofShow { get; set; }

    [Column("IndM_PeriodofShow")]
    public int? IndMPeriodofShow { get; set; }
}