// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblIndicatorOtherDataCategory")]
public partial class TblIndicatorOtherDataCategory
{
    [Key]
    [Column("OtherDataCategory_ID")]
    public int OtherDataCategoryId { get; set; }

    [Column("OtherDataCategory_NameAr")]
    [StringLength(150)]
    public string OtherDataCategoryNameAr { get; set; }

    [Column("OtherDataCategory_NameEn")]
    [StringLength(150)]
    public string OtherDataCategoryNameEn { get; set; }
}