// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblIndicatorActivity")]
public partial class TblIndicatorActivity
{
    [Key]
    [Column("Activity_ID")]
    public int ActivityId { get; set; }

    [Column("Activity_NameAr")]
    public string ActivityNameAr { get; set; }

    [Column("Activity_NameEn")]
    public string ActivityNameEn { get; set; }
}