// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblIndicatorUrban")]
public partial class TblIndicatorUrban
{
    [Key]
    [Column("Urban_ID")]
    public int UrbanId { get; set; }

    [Column("Urban_NameAr")]
    [StringLength(10)]
    public string UrbanNameAr { get; set; }

    [Column("Urban_NameEn")]
    [StringLength(10)]
    public string UrbanNameEn { get; set; }
}