// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblIndicators")]
public partial class TblIndicator
{
    [Key]
    [Column("Ind_ID")]
    public int IndId { get; set; }

    [Column("Ind_NameAr")]
    public string IndNameAr { get; set; }

    [Column("Ind_NameEn")]
    public string IndNameEn { get; set; }

    [Column("Ind_DescAr", TypeName = "text")]
    public string IndDescAr { get; set; }

    [Column("Ind_DescEn", TypeName = "text")]
    public string IndDescEn { get; set; }

    [Column("Ind_IdentifyAr")]
    public string IndIdentifyAr { get; set; }

    [Column("Ind_IdentifyEn")]
    public string IndIdentifyEn { get; set; }

    [Column("Ind_CalcMethodAr")]
    public string IndCalcMethodAr { get; set; }

    [Column("Ind_CalcMethodEn")]
    public string IndCalcMethodEn { get; set; }

    [Column("Ind_DataSourceAr")]
    public string IndDataSourceAr { get; set; }

    [Column("Ind_DataSourceEn")]
    public string IndDataSourceEn { get; set; }

    [Column("Ind_MethodologyAr")]
    public string IndMethodologyAr { get; set; }

    [Column("Ind_MethodologyEn")]
    public string IndMethodologyEn { get; set; }

    [Column("Ind_KeyWordsAr")]
    public string IndKeyWordsAr { get; set; }

    [Column("Ind_KeyWordsEn")]
    public string IndKeyWordsEn { get; set; }

    [Column("Period_ID_Collection")]
    public int? PeriodIdCollection { get; set; }

    [Column("Period_ID_Publish")]
    public int? PeriodIdPublish { get; set; }

    [Column("Side_ID_Collection")]
    public int? SideIdCollection { get; set; }

    [Column("Side_ID_Production")]
    public int? SideIdProduction { get; set; }

    [Column("Side_ID_Publish")]
    public int? SideIdPublish { get; set; }

    [Column("Ind_Visible")]
    public bool? IndVisible { get; set; }

    [Column("SB_ID")]
    public int? SbId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("Ind_ShowForStatistics")]
    public bool? IndShowForStatistics { get; set; }

    [Column("Ind_ShowForTimeSeries")]
    public bool? IndShowForTimeSeries { get; set; }

    [Column("Ind_Scale")]
    public int? IndScale { get; set; }

    [Column("Ind_YaxisName")]
    [StringLength(100)]
    public string IndYaxisName { get; set; }

    [Column("Ind_YaxisName_En")]
    [StringLength(100)]
    public string IndYaxisNameEn { get; set; }

    [Column("Ind_DecimalNo")]
    public int? IndDecimalNo { get; set; }

    [Column("Internal_Show")]
    public bool? InternalShow { get; set; }

    [InverseProperty("Ind")]
    public virtual ICollection<IndicatorsUsersPriviliage> IndicatorsUsersPriviliages { get; set; } = new List<IndicatorsUsersPriviliage>();

    [InverseProperty("Ind")]
    public virtual ICollection<TblImportantIndicator> TblImportantIndicators { get; set; } = new List<TblImportantIndicator>();
}