// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblMainPublication")]
public partial class TblMainPublication
{
    [Key]
    [Column("Pub_ID")]
    public int PubId { get; set; }

    [Column("Pub_NameAr")]
    [StringLength(50)]
    public string PubNameAr { get; set; }

    [Column("Pub_NameEn")]
    [StringLength(50)]
    public string PubNameEn { get; set; }

    [Column("Pub_DescAr")]
    [StringLength(150)]
    public string PubDescAr { get; set; }

    [Column("Pub_DescEn")]
    [StringLength(150)]
    public string PubDescEn { get; set; }

    [Column("Pub_PublishDateAr")]
    [StringLength(50)]
    public string PubPublishDateAr { get; set; }

    [Column("Pub_PublishDateEn")]
    [StringLength(50)]
    public string PubPublishDateEn { get; set; }

    [Column("Pub_Order")]
    public int? PubOrder { get; set; }

    [Column("Pub_Link")]
    [StringLength(100)]
    public string PubLink { get; set; }

    [Column("Pub_ImageLinkAr")]
    [StringLength(150)]
    public string PubImageLinkAr { get; set; }

    [Column("Pub_ImageLinkEn")]
    [StringLength(150)]
    public string PubImageLinkEn { get; set; }

    [Column("Pub_Visible")]
    public bool? PubVisible { get; set; }

    [Column("Pub_InternalShow")]
    public bool? PubInternalShow { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblMainPublicationEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblMainPublicationEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }
}