// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblMonths")]
public partial class TblMonth
{
    [Key]
    [Column("Month_ID")]
    public int MonthId { get; set; }

    [Column("Month_NameAr")]
    [StringLength(10)]
    public string MonthNameAr { get; set; }

    [Column("Month_NameEn")]
    [StringLength(10)]
    public string MonthNameEn { get; set; }

    [InverseProperty("Month")]
    public virtual ICollection<HistoryDetail> HistoryDetails { get; set; } = new List<HistoryDetail>();

    [InverseProperty("Month")]
    public virtual ICollection<TblStatistcalBulltinsYear> TblStatistcalBulltinsYears { get; set; } = new List<TblStatistcalBulltinsYear>();
}