// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblMainSubMenu")]
public partial class TblMainSubMenu
{
    [Key]
    [Column("MSM_ID")]
    public int MsmId { get; set; }

    [Column("MM_ID")]
    public int MmId { get; set; }

    [Column("MSMGrp_ID")]
    public int? MsmgrpId { get; set; }

    [Required]
    [Column("MSM_ArName")]
    [StringLength(100)]
    public string MsmArName { get; set; }

    [Required]
    [Column("MSM_EnName")]
    [StringLength(100)]
    public string MsmEnName { get; set; }

    [Required]
    [Column("MSM_Visable")]
    public bool? MsmVisable { get; set; }

    [Column("MSM_EnglishVisible")]
    public bool? MsmEnglishVisible { get; set; }

    [Column("MSM_Restricted")]
    public bool? MsmRestricted { get; set; }

    [Required]
    [Column("MSM_Link")]
    [StringLength(255)]
    public string MsmLink { get; set; }

    [Column("MSM_IconLink")]
    [StringLength(150)]
    public string MsmIconLink { get; set; }

    [Column("MSM_Order")]
    public int? MsmOrder { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblMainSubMenuEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblMainSubMenuEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [InverseProperty("Msm")]
    public virtual ICollection<HistoryCategory> HistoryCategories { get; set; } = new List<HistoryCategory>();

    [ForeignKey("MmId")]
    [InverseProperty("TblMainSubMenus")]
    public virtual TblMainMenu Mm { get; set; }

    [ForeignKey("MsmgrpId")]
    [InverseProperty("TblMainSubMenus")]
    public virtual TblMainSubMenuGroup Msmgrp { get; set; }

    [InverseProperty("Msm")]
    public virtual ICollection<TblFormCategory> TblFormCategories { get; set; } = new List<TblFormCategory>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblNewsTypesMainSubMenu> TblNewsTypesMainSubMenus { get; set; } = new List<TblNewsTypesMainSubMenu>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblPage> TblPages { get; set; } = new List<TblPage>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblPaperCategory> TblPaperCategories { get; set; } = new List<TblPaperCategory>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblPermission> TblPermissions { get; set; } = new List<TblPermission>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblQuestion> TblQuestions { get; set; } = new List<TblQuestion>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblRequestCategory> TblRequestCategories { get; set; } = new List<TblRequestCategory>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblReseachAndFormsCategory> TblReseachAndFormsCategories { get; set; } = new List<TblReseachAndFormsCategory>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblSemanticIssue> TblSemanticIssueMsms { get; set; } = new List<TblSemanticIssue>();

    [InverseProperty("Smsm")]
    public virtual ICollection<TblSemanticIssue> TblSemanticIssueSmsms { get; set; } = new List<TblSemanticIssue>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblSiteCategory> TblSiteCategories { get; set; } = new List<TblSiteCategory>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblStatisticsBulltin> TblStatisticsBulltins { get; set; } = new List<TblStatisticsBulltin>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblStatisticsDepartement> TblStatisticsDepartements { get; set; } = new List<TblStatisticsDepartement>();

    [InverseProperty("Msm")]
    public virtual ICollection<TblUserFav> TblUserFavs { get; set; } = new List<TblUserFav>();
}