// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblMainSubMenu_Group")]
public partial class TblMainSubMenuGroup
{
    [Key]
    [Column("MSMGrp_ID")]
    public int MsmgrpId { get; set; }

    [Column("MSMGrp_NameAr")]
    [StringLength(150)]
    public string MsmgrpNameAr { get; set; }

    [Column("MSMGrp_NameEn")]
    [StringLength(150)]
    public string MsmgrpNameEn { get; set; }

    [Column("MSMGrp_Image")]
    [StringLength(150)]
    public string MsmgrpImage { get; set; }

    [Column("MM_ID")]
    public int? MmId { get; set; }

    [Column("MSMGrp_Order")]
    public int? MsmgrpOrder { get; set; }

    [ForeignKey("MmId")]
    [InverseProperty("TblMainSubMenuGroups")]
    public virtual TblMainMenu Mm { get; set; }

    [InverseProperty("Msmgrp")]
    public virtual ICollection<TblMainSubMenu> TblMainSubMenus { get; set; } = new List<TblMainSubMenu>();
}