// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblNewsFiles")]
[Index("NewsId", Name = "IX_tblNewsFiles_News_ID")]
public partial class TblNewsFile
{
    [Key]
    [Column("NL_ID")]
    public int NlId { get; set; }

    [Column("News_ID")]
    public int? NewsId { get; set; }

    [Column("NL_NameAr")]
    [StringLength(100)]
    public string NlNameAr { get; set; }

    [Column("NL_NameEn")]
    [StringLength(100)]
    public string NlNameEn { get; set; }

    [Column("NL_LinkAr")]
    [StringLength(150)]
    public string NlLinkAr { get; set; }

    [Column("NL_LinkEn")]
    [StringLength(150)]
    public string NlLinkEn { get; set; }

    [Column("NL_Visable")]
    public bool? NlVisable { get; set; }

    [Column("NL_VisibleEnglish")]
    public bool? NlVisibleEnglish { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("NL_PageLink")]
    public bool? NlPageLink { get; set; }

    [Column("NL_Page", TypeName = "text")]
    public string NlPage { get; set; }

    [Column("NL_PAgeEn", TypeName = "text")]
    public string NlPageEn { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblNewsFileEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblNewsFileEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("NewsId")]
    [InverseProperty("TblNewsFiles")]
    public virtual TblNews News { get; set; }
}