// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblNewsTypes")]
public partial class TblNewsType
{
    [Key]
    [Column("Type_ID")]
    public int TypeId { get; set; }

    [Column("Type_NameEn")]
    [StringLength(50)]
    public string TypeNameEn { get; set; }

    [Column("Type_NameAr")]
    [StringLength(50)]
    public string TypeNameAr { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblNewsTypeEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblNewsTypeEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<TblNewsTypesMainSubMenu> TblNewsTypesMainSubMenus { get; set; } = new List<TblNewsTypesMainSubMenu>();
}