// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblNews")]
public partial class TblNews
{
    [Key]
    [Column("News_ID")]
    public int NewsId { get; set; }

    [Required]
    [Column("News_NameAr")]
    [StringLength(200)]
    public string NewsNameAr { get; set; }

    [Required]
    [Column("News_NameEn")]
    [StringLength(200)]
    public string NewsNameEn { get; set; }

    [Column("News_Period")]
    [StringLength(50)]
    public string NewsPeriod { get; set; }

    [Column("News_BriefAr")]
    public string NewsBriefAr { get; set; }

    [Column("News_BriefEn")]
    public string NewsBriefEn { get; set; }

    [Column("News_Link")]
    [StringLength(100)]
    public string NewsLink { get; set; }

    [Column("News_PublishDate", TypeName = "datetime")]
    public DateTime? NewsPublishDate { get; set; }

    [Column("News_CreatedDate", TypeName = "datetime")]
    public DateTime? NewsCreatedDate { get; set; }

    [Column("News_IconLink")]
    [StringLength(100)]
    public string NewsIconLink { get; set; }

    [Column("News_Visible")]
    public bool? NewsVisible { get; set; }

    [Column("News_VisibleEnglish")]
    public bool? NewsVisibleEnglish { get; set; }

    [Column("News_InternalShow")]
    public bool? NewsInternalShow { get; set; }

    [Column("News_Tab")]
    public bool? NewsTab { get; set; }

    [Column("NTM_ID")]
    public int? NtmId { get; set; }

    [Column("SBY_ID")]
    public int? SbyId { get; set; }

    [Column("News_IsPublished")]
    public bool? NewsIsPublished { get; set; }

    [Column("News_ShowinMain")]
    public bool? NewsShowinMain { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("News_IndNumber")]
    [StringLength(50)]
    public string NewsIndNumber { get; set; }

    [Column("News_IndDateAr")]
    [StringLength(50)]
    public string NewsIndDateAr { get; set; }

    [Column("News_IndDateEn")]
    [StringLength(50)]
    public string NewsIndDateEn { get; set; }

    [Column("News_ShowInHotIssue")]
    public bool? NewsShowInHotIssue { get; set; }

    [Column("News_ShowInEvents")]
    public bool? NewsShowInEvents { get; set; }

    [Column("Internal_Show")]
    public bool? InternalShow { get; set; }

    [Column("News_DateofShow", TypeName = "datetime")]
    public DateTime? NewsDateofShow { get; set; }

    [Column("News_PeriodofShow")]
    public int? NewsPeriodofShow { get; set; }

    [ForeignKey("NtmId")]
    [InverseProperty("TblNews")]
    public virtual TblNewsTypesMainSubMenu Ntm { get; set; }

    [InverseProperty("News")]
    public virtual ICollection<TblNewsFile> TblNewsFiles { get; set; } = new List<TblNewsFile>();
}