// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblNewsGroup")]
public partial class TblNewsGroup
{
    [Key]
    [Column("Group_ID")]
    public int GroupId { get; set; }

    [Column("Group_Name")]
    [StringLength(50)]
    public string GroupName { get; set; }
}