// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblOrderFormSides")]
public partial class TblOrderFormSide
{
    [Key]
    [Column("ROS_ID")]
    public int RosId { get; set; }

    [Column("ROS_CreatedDate", TypeName = "datetime")]
    public DateTime? RosCreatedDate { get; set; }

    [Column("ROS_SideName")]
    [StringLength(150)]
    public string RosSideName { get; set; }

    [Column("ROS_Sector")]
    [StringLength(100)]
    public string RosSector { get; set; }

    [Column("ROS_Activity")]
    [StringLength(100)]
    public string RosActivity { get; set; }

    [Column("ROS_Address")]
    [StringLength(250)]
    public string RosAddress { get; set; }

    [Column("ROS_Responsable")]
    [StringLength(50)]
    public string RosResponsable { get; set; }

    [Column("ROS_PhoneNo")]
    [StringLength(50)]
    public string RosPhoneNo { get; set; }

    [Column("ROS_MobileNo")]
    [StringLength(50)]
    public string RosMobileNo { get; set; }

    [Column("ROS_FaxNo")]
    [StringLength(50)]
    public string RosFaxNo { get; set; }

    [Column("ROS_Email")]
    [StringLength(50)]
    public string RosEmail { get; set; }

    [Column("ROS_RequestOrder")]
    [StringLength(150)]
    public string RosRequestOrder { get; set; }

    [Column("ROS_OrderGoal")]
    [StringLength(250)]
    public string RosOrderGoal { get; set; }

    [Column("ROS_OrderSide")]
    [StringLength(50)]
    public string RosOrderSide { get; set; }

    [Column("ROS_UserID")]
    public int? RosUserId { get; set; }
}