// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblPopulationClock")]
public partial class TblPopulationClock
{
    [Key]
    [Column("PopC_ID")]
    public int PopCId { get; set; }

    [Column("PopC_NameAr")]
    [StringLength(50)]
    public string PopCNameAr { get; set; }

    [Column("PopC_NameEn")]
    [StringLength(50)]
    public string PopCNameEn { get; set; }

    [Column("PopC_IconLink")]
    [StringLength(150)]
    public string PopCIconLink { get; set; }

    [Column("PopC_Value")]
    [StringLength(20)]
    public string PopCValue { get; set; }

    [Column("PopC_Base")]
    [StringLength(12)]
    public string PopCBase { get; set; }

    [Column("PopC_Date", TypeName = "datetime")]
    public DateTime? PopCDate { get; set; }

    [Column("PopC_Hours")]
    public int? PopCHours { get; set; }

    [Column("PopC_IsShow")]
    public bool? PopCIsShow { get; set; }

    [Column("PopC_IsShowEn")]
    public bool? PopCIsShowEn { get; set; }

    [Column("Gov_ID")]
    public int? GovId { get; set; }

    [Column("PopC_Order")]
    public int? PopCOrder { get; set; }

    [Column("Map_Code")]
    [StringLength(50)]
    public string MapCode { get; set; }

    public long? NewClockValue { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdateTime { get; set; }

    [ForeignKey("GovId")]
    [InverseProperty("TblPopulationClocks")]
    public virtual TblGovernorate Gov { get; set; }
}