// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblPages")]
public partial class TblPage
{
    [Key]
    [Column("Pag_ID")]
    public int PagId { get; set; }

    [Required]
    [Column("Pag_Contents", TypeName = "text")]
    public string PagContents { get; set; }

    [Column("Pag_File")]
    [StringLength(150)]
    public string PagFile { get; set; }

    [Column("Pag_Tiltle")]
    [StringLength(100)]
    public string PagTiltle { get; set; }

    [Column("Pag_BriefDesc")]
    [StringLength(500)]
    public string PagBriefDesc { get; set; }

    [Column("MSM_ID")]
    public int? MsmId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("pag_order")]
    public int? PagOrder { get; set; }

    [Column("Pag_Tiltle_En")]
    [StringLength(100)]
    public string PagTiltleEn { get; set; }

    [Column("Pag_BriefDesc_En")]
    [StringLength(500)]
    public string PagBriefDescEn { get; set; }

    [Column("Pag_Contents_En", TypeName = "text")]
    public string PagContentsEn { get; set; }

    [Column("Pag_File_En")]
    [StringLength(150)]
    public string PagFileEn { get; set; }

    [Column("Pag_Restricted")]
    public bool? PagRestricted { get; set; }

    [Column("pag_Visible")]
    public bool? PagVisible { get; set; }

    [Column("pag_InternalShow")]
    public bool? PagInternalShow { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblPageEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblPageEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("MsmId")]
    [InverseProperty("TblPages")]
    public virtual TblMainSubMenu Msm { get; set; }
}