// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblPublicationTypes")]
public partial class TblPublicationType
{
    [Key]
    [Column("PubT_ID")]
    public int PubTId { get; set; }

    [Column("PubT_NameAr")]
    [StringLength(80)]
    public string PubTNameAr { get; set; }

    [Column("PubT_NameEn")]
    [StringLength(80)]
    public string PubTNameEn { get; set; }

    [InverseProperty("PubT")]
    public virtual ICollection<TblStatisticsBulltin> TblStatisticsBulltins { get; set; } = new List<TblStatisticsBulltin>();
}