// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblPagesSectors")]
public partial class TblPagesSector
{
    [Key]
    [Column("PS_ID")]
    public int PsId { get; set; }

    [Column("PS_ArName")]
    [StringLength(50)]
    public string PsArName { get; set; }

    [Column("PS_EnName")]
    [StringLength(50)]
    public string PsEnName { get; set; }

    [Column("PS_Visable")]
    public bool? PsVisable { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblPagesSectorEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblPagesSectorEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [InverseProperty("Ps")]
    public virtual ICollection<TblMainPagesSector> TblMainPagesSectors { get; set; } = new List<TblMainPagesSector>();
}