// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblPeriods")]
public partial class TblPeriod
{
    [Key]
    [Column("Per_ID")]
    public int PerId { get; set; }

    [Column("Per_NameAr")]
    [StringLength(150)]
    public string PerNameAr { get; set; }

    [Column("Per_NameEn")]
    [StringLength(150)]
    public string PerNameEn { get; set; }

    [Column("Per_IndVisible")]
    public bool? PerIndVisible { get; set; }

    [Column("Per_Order")]
    public int? PerOrder { get; set; }

    [InverseProperty("Per")]
    public virtual ICollection<HistoryDetail> HistoryDetails { get; set; } = new List<HistoryDetail>();
}