// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblPapers")]
public partial class TblPaper
{
    [Key]
    [Column("Pap_ID")]
    public int PapId { get; set; }

    [Column("Pap_Name")]
    [StringLength(50)]
    public string PapName { get; set; }

    [Column("Emp_ID")]
    public int? EmpId { get; set; }

    [Column("Pap_Link")]
    [StringLength(150)]
    public string PapLink { get; set; }

    [Column("Pap_Year", TypeName = "date")]
    public DateTime? PapYear { get; set; }

    [Column("PC_ID")]
    public int? PcId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpId")]
    [InverseProperty("TblPaperEmps")]
    public virtual TblEmployee Emp { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblPaperEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblPaperEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("PcId")]
    [InverseProperty("TblPapers")]
    public virtual TblPaperCategory Pc { get; set; }
}