// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblPosition")]
public partial class TblPosition
{
    [Key]
    [Column("Pos_ID")]
    public int PosId { get; set; }

    [Column("Pos_Name")]
    [StringLength(50)]
    public string PosName { get; set; }

    [Column("Man_ID")]
    public int? ManId { get; set; }

    [ForeignKey("ManId")]
    [InverseProperty("TblPositions")]
    public virtual TblCapmasmangement Man { get; set; }

    [InverseProperty("Pos")]
    public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
}