// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQuestionEvaluation")]
public partial class TblQuestionEvaluation
{
    [Key]
    [Column("Evaluation_ID")]
    public int EvaluationId { get; set; }

    [Column("Evaluation_NameAr")]
    [StringLength(50)]
    public string EvaluationNameAr { get; set; }

    [Column("Evaluation_NameEn")]
    [StringLength(50)]
    public string EvaluationNameEn { get; set; }

    [InverseProperty("Evaluation")]
    public virtual ICollection<TblQuestion> TblQuestions { get; set; } = new List<TblQuestion>();
}