// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQuestionStatus")]
public partial class TblQuestionStatus
{
    [Key]
    [Column("Status_ID")]
    public int StatusId { get; set; }

    [Column("Status_NameAr")]
    [StringLength(50)]
    public string StatusNameAr { get; set; }

    [Column("Status_NameEn")]
    [StringLength(50)]
    public string StatusNameEn { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<TblQuestion> TblQuestions { get; set; } = new List<TblQuestion>();
}