// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQuestsioner_Answers")]
public partial class TblQuestsionerAnswer
{
    [Key]
    [Column("QA_ID")]
    public int QaId { get; set; }

    [Column("QO_ID")]
    public int? QoId { get; set; }

    [Column("QA_Others")]
    [StringLength(150)]
    public string QaOthers { get; set; }

    [Column("User_ID")]
    public int? UserId { get; set; }

    [Column("QA_Date", TypeName = "datetime")]
    public DateTime? QaDate { get; set; }

    [ForeignKey("QoId")]
    [InverseProperty("TblQuestsionerAnswers")]
    public virtual TblQuestsionerDatum Qo { get; set; }
}