// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQualifications")]
public partial class TblQualification
{
    [Key]
    [Column("Quali_ID")]
    public int QualiId { get; set; }

    [Column("Quali_NameAr")]
    [StringLength(50)]
    public string QualiNameAr { get; set; }

    [Column("Quali_NameEn")]
    [StringLength(50)]
    public string QualiNameEn { get; set; }

    [InverseProperty("Quali")]
    public virtual ICollection<TblApplicationOld> TblApplicationOlds { get; set; } = new List<TblApplicationOld>();
}