// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQuestsioner_Data")]
public partial class TblQuestsionerDatum
{
    [Key]
    [Column("QO_ID")]
    public int QoId { get; set; }

    [Column("QT_ID")]
    public int? QtId { get; set; }

    [Column("QO_NameAr")]
    [StringLength(50)]
    public string QoNameAr { get; set; }

    [Column("QO_NameEn")]
    [StringLength(50)]
    public string QoNameEn { get; set; }

    [Column("QO_Choice")]
    public bool? QoChoice { get; set; }

    [ForeignKey("QtId")]
    [InverseProperty("TblQuestsionerData")]
    public virtual TblQuestsionerTitle Qt { get; set; }

    [InverseProperty("Qo")]
    public virtual ICollection<TblQuestsionerAnswer> TblQuestsionerAnswers { get; set; } = new List<TblQuestsionerAnswer>();
}