// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQuestionClusters")]
public partial class TblQuestionCluster
{
    [Key]
    [Column("QC_ID")]
    public int QcId { get; set; }

    [Column("QC_NameAr")]
    [StringLength(100)]
    public string QcNameAr { get; set; }

    [Column("QC_NameEn")]
    [StringLength(100)]
    public string QcNameEn { get; set; }

    [InverseProperty("Qc")]
    public virtual ICollection<TblQuestion> TblQuestions { get; set; } = new List<TblQuestion>();
}