// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQuestions")]
public partial class TblQuestion
{
    [Key]
    [Column("Que_ID")]
    public int QueId { get; set; }

    [Column("Que_Title")]
    [StringLength(100)]
    public string QueTitle { get; set; }

    [Column("Que_Text")]
    [StringLength(500)]
    public string QueText { get; set; }

    [Column("Que_Mangement")]
    [StringLength(200)]
    public string QueMangement { get; set; }

    [Column("Status_ID")]
    public int? StatusId { get; set; }

    [Column("QC_ID")]
    public int QcId { get; set; }

    [Column("Que_Date", TypeName = "datetime")]
    public DateTime? QueDate { get; set; }

    [Column("Que_Answered")]
    public string QueAnswered { get; set; }

    [Column("Que_Finished")]
    public bool? QueFinished { get; set; }

    [Column("Que_Evaluated")]
    public bool? QueEvaluated { get; set; }

    [Column("Man_ID")]
    public int? ManId { get; set; }

    [Column("Que_Internal")]
    public bool? QueInternal { get; set; }

    [Column("Que_Type")]
    public int? QueType { get; set; }

    [Column("MSM_ID")]
    public int? MsmId { get; set; }

    [Column("Usr_ID")]
    public int? UsrId { get; set; }

    [Column("Que_Visible")]
    public bool? QueVisible { get; set; }

    [Column("Que_File1")]
    [StringLength(150)]
    public string QueFile1 { get; set; }

    [Column("Que_File2")]
    [StringLength(150)]
    public string QueFile2 { get; set; }

    [Column("Evaluation_ID")]
    public int? EvaluationId { get; set; }

    [Column("Que_SendMail")]
    public bool? QueSendMail { get; set; }

    [ForeignKey("EvaluationId")]
    [InverseProperty("TblQuestions")]
    public virtual TblQuestionEvaluation Evaluation { get; set; }

    [ForeignKey("ManId")]
    [InverseProperty("TblQuestions")]
    public virtual TblCapmasmangement Man { get; set; }

    [ForeignKey("MsmId")]
    [InverseProperty("TblQuestions")]
    public virtual TblMainSubMenu Msm { get; set; }

    [ForeignKey("QcId")]
    [InverseProperty("TblQuestions")]
    public virtual TblQuestionCluster Qc { get; set; }

    [InverseProperty("Que")]
    public virtual ICollection<QuestionLink> QuestionLinks { get; set; } = new List<QuestionLink>();

    [ForeignKey("StatusId")]
    [InverseProperty("TblQuestions")]
    public virtual TblQuestionStatus Status { get; set; }

    [InverseProperty("Que")]
    public virtual ICollection<TblUseMessage> TblUseMessages { get; set; } = new List<TblUseMessage>();

    [ForeignKey("UsrId")]
    [InverseProperty("TblQuestions")]
    public virtual TblUser Usr { get; set; }
}