// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblQuestsioner_Titles")]
public partial class TblQuestsionerTitle
{
    [Key]
    [Column("QT_ID")]
    public int QtId { get; set; }

    [Column("QT_NameAr")]
    [StringLength(150)]
    public string QtNameAr { get; set; }

    [Column("QT_NameEn")]
    [StringLength(150)]
    public string QtNameEn { get; set; }

    [Column("QT_CreatedDate", TypeName = "datetime")]
    public DateTime? QtCreatedDate { get; set; }

    [Column("QT_Visable")]
    public bool? QtVisable { get; set; }

    [InverseProperty("Qt")]
    public virtual ICollection<TblQuestsionerDatum> TblQuestsionerData { get; set; } = new List<TblQuestsionerDatum>();
}