// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblResearchLinks")]
public partial class TblResearchLink
{
    [Key]
    [Column("RL_ID")]
    public int RlId { get; set; }

    [Column("RL_TitleAr")]
    [StringLength(250)]
    public string RlTitleAr { get; set; }

    [Column("RL_TitleEn")]
    [StringLength(250)]
    public string RlTitleEn { get; set; }

    [Column("RL_LinkAr")]
    [StringLength(250)]
    public string RlLinkAr { get; set; }

    [Column("RL_LinkEn")]
    [StringLength(250)]
    public string RlLinkEn { get; set; }

    [Column("RY_ID")]
    public int? RyId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblResearchLinkEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblResearchLinkEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("RyId")]
    [InverseProperty("TblResearchLinks")]
    public virtual TblReserchesAndFormsYear Ry { get; set; }
}