// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblRequests")]
public partial class TblRequest
{
    [Key]
    [Column("Job_ID")]
    public int JobId { get; set; }

    [Column("Job_NameAr")]
    [StringLength(150)]
    public string JobNameAr { get; set; }

    [Column("Request_NameEn")]
    [StringLength(150)]
    public string RequestNameEn { get; set; }

    [Column("Request_DescAr", TypeName = "text")]
    public string RequestDescAr { get; set; }

    [Column("Request_DescEn", TypeName = "text")]
    public string RequestDescEn { get; set; }

    [Column("Request_GuestListAr", TypeName = "text")]
    public string RequestGuestListAr { get; set; }

    [Column("Request_GuestListEn", TypeName = "text")]
    public string RequestGuestListEn { get; set; }

    [Column("Request_PublishDate", TypeName = "date")]
    public DateTime? RequestPublishDate { get; set; }

    [Column("Request_FinishDate", TypeName = "date")]
    public DateTime? RequestFinishDate { get; set; }

    [Column("Request_Visible")]
    public bool? RequestVisible { get; set; }

    [Column("Request_Price")]
    [StringLength(50)]
    public string RequestPrice { get; set; }

    [Column("RequestC_ID")]
    public int? RequestCId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblRequestEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblRequestEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("RequestCId")]
    [InverseProperty("TblRequests")]
    public virtual TblRequestCategory RequestC { get; set; }

    [InverseProperty("Request")]
    public virtual ICollection<TblRequestRegisteration> TblRequestRegisterations { get; set; } = new List<TblRequestRegisteration>();
}