// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblRequestRegisteration")]
public partial class TblRequestRegisteration
{
    [Key]
    [Column("JR_ID")]
    public int JrId { get; set; }

    [Column("JR_CVAttach")]
    [StringLength(150)]
    public string JrCvattach { get; set; }

    [Column("RequestReg_IdentityAttach")]
    [StringLength(150)]
    public string RequestRegIdentityAttach { get; set; }

    [Column("RequestReg_CertificationAttach")]
    [StringLength(150)]
    public string RequestRegCertificationAttach { get; set; }

    [Column("RequestReg_University")]
    [StringLength(100)]
    public string RequestRegUniversity { get; set; }

    [Column("RequestReg_Faculty")]
    [StringLength(100)]
    public string RequestRegFaculty { get; set; }

    [Column("RequestReg_Department")]
    [StringLength(100)]
    public string RequestRegDepartment { get; set; }

    [Column("RequestReg_HighStudies")]
    [StringLength(200)]
    public string RequestRegHighStudies { get; set; }

    [Column("EC_ID")]
    public int? EcId { get; set; }

    [Column("Usr_ID")]
    public int? UsrId { get; set; }

    [Column("RS_ID")]
    public int? RsId { get; set; }

    [Column("Request_ID")]
    public int? RequestId { get; set; }

    [Column("RequestReg_Shown")]
    public bool? RequestRegShown { get; set; }

    [Column("RequestReg_SendMail")]
    public bool? RequestRegSendMail { get; set; }

    [Column("RequestReg_Answer", TypeName = "text")]
    public string RequestRegAnswer { get; set; }

    [Column("Emp_ID")]
    public int? EmpId { get; set; }

    [Column("Emp_AnswerDate", TypeName = "datetime")]
    public DateTime? EmpAnswerDate { get; set; }

    [ForeignKey("EcId")]
    [InverseProperty("TblRequestRegisterations")]
    public virtual TblEducationCategory Ec { get; set; }

    [ForeignKey("EmpId")]
    [InverseProperty("TblRequestRegisterations")]
    public virtual TblEmployee Emp { get; set; }

    [ForeignKey("RequestId")]
    [InverseProperty("TblRequestRegisterations")]
    public virtual TblRequest Request { get; set; }

    [ForeignKey("RsId")]
    [InverseProperty("TblRequestRegisterations")]
    public virtual TblRequestStatus Rs { get; set; }

    [ForeignKey("UsrId")]
    [InverseProperty("TblRequestRegisterations")]
    public virtual TblUser Usr { get; set; }
}