// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblResearchesAgreement")]
public partial class TblResearchesAgreement
{
    [Key]
    [Column("Ra_ID")]
    public int RaId { get; set; }

    [Column("Ra_SideAr")]
    [StringLength(250)]
    public string RaSideAr { get; set; }

    [Column("Ra_SideEn")]
    [StringLength(250)]
    public string RaSideEn { get; set; }

    [Column("Ra_TopicAr")]
    public string RaTopicAr { get; set; }

    [Column("Ra_TopicEn")]
    public string RaTopicEn { get; set; }

    [Column("Ra_SampleValueAr")]
    [StringLength(50)]
    public string RaSampleValueAr { get; set; }

    [Column("Ra_SampleValueEn")]
    [StringLength(50)]
    public string RaSampleValueEn { get; set; }

    [Column("Ra_GovNumbersAr")]
    [StringLength(50)]
    public string RaGovNumbersAr { get; set; }

    [Column("Ra_GovNumbersEn")]
    [StringLength(50)]
    public string RaGovNumbersEn { get; set; }

    [Column("Ra_FromDate", TypeName = "datetime")]
    public DateTime? RaFromDate { get; set; }

    [Column("Ra_ToDate", TypeName = "datetime")]
    public DateTime? RaToDate { get; set; }

    [Column("Fo_ID")]
    public int? FoId { get; set; }

    [Column("Internal_Show")]
    public bool? InternalShow { get; set; }

    [Column("Ra_Visible")]
    public bool? RaVisible { get; set; }

    [Column("Ra_Publish")]
    public bool? RaPublish { get; set; }

    [ForeignKey("FoId")]
    [InverseProperty("TblResearchesAgreements")]
    public virtual TblFoundation Fo { get; set; }
}