// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblRequestFormSides")]
public partial class TblRequestFormSide
{
    [Key]
    [Column("RFS_ID")]
    public int RfsId { get; set; }

    [Column("RFS_CreatedDate", TypeName = "datetime")]
    public DateTime? RfsCreatedDate { get; set; }

    [Column("RFS_SideName")]
    [StringLength(150)]
    public string RfsSideName { get; set; }

    [Column("RFS_Sector")]
    [StringLength(100)]
    public string RfsSector { get; set; }

    [Column("RFS_Activity")]
    [StringLength(100)]
    public string RfsActivity { get; set; }

    [Column("RFS_Address")]
    [StringLength(250)]
    public string RfsAddress { get; set; }

    [Column("RFS_Responsable")]
    [StringLength(50)]
    public string RfsResponsable { get; set; }

    [Column("RFS_PhoneNo")]
    [StringLength(50)]
    public string RfsPhoneNo { get; set; }

    [Column("RFS_MobileNo")]
    [StringLength(50)]
    public string RfsMobileNo { get; set; }

    [Column("RFS_FaxNo")]
    [StringLength(50)]
    public string RfsFaxNo { get; set; }

    [Column("RFS_Email")]
    [StringLength(50)]
    public string RfsEmail { get; set; }

    [Column("RFS_ResearchTitle")]
    [StringLength(100)]
    public string RfsResearchTitle { get; set; }

    [Column("RFS_ResearchGoal")]
    public string RfsResearchGoal { get; set; }

    [Column("RFS_DocumentsNo")]
    [StringLength(50)]
    public string RfsDocumentsNo { get; set; }

    [Column("RFS_Society")]
    [StringLength(100)]
    public string RfsSociety { get; set; }

    [Column("RFS_SampleSize")]
    [StringLength(50)]
    public string RfsSampleSize { get; set; }

    [Column("RFS_StudyPeriod")]
    [StringLength(50)]
    public string RfsStudyPeriod { get; set; }

    [Column("RFS_OtherSideName")]
    [StringLength(150)]
    public string RfsOtherSideName { get; set; }

    [Column("RFS_OtherSector")]
    [StringLength(100)]
    public string RfsOtherSector { get; set; }

    [Column("RFS_OtherActivity")]
    [StringLength(100)]
    public string RfsOtherActivity { get; set; }

    [Column("RFS_UserID")]
    public int? RfsUserId { get; set; }
}