// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblReserchesAndFormsYear")]
[Index("RchId", Name = "IX_tblReserchesAndFormsYear_Rch_ID")]
public partial class TblReserchesAndFormsYear
{
    [Key]
    [Column("RY_ID")]
    public int RyId { get; set; }

    [Column("RY_CreatedDate", TypeName = "datetime")]
    public DateTime? RyCreatedDate { get; set; }

    [Column("Rch_ID")]
    public int? RchId { get; set; }

    [Column("Year_ID")]
    public int? YearId { get; set; }

    [Column("RY_TitleAr")]
    [StringLength(250)]
    public string RyTitleAr { get; set; }

    [Column("RY_BriefDescAr")]
    public string RyBriefDescAr { get; set; }

    [Column("RY_ScopeAr")]
    public string RyScopeAr { get; set; }

    [Column("RY_TitleEn")]
    [StringLength(250)]
    public string RyTitleEn { get; set; }

    [Column("RY_BriefDescEn")]
    public string RyBriefDescEn { get; set; }

    [Column("RY_ScopeEn")]
    public string RyScopeEn { get; set; }

    [Column("RY_StudyDate")]
    [StringLength(50)]
    public string RyStudyDate { get; set; }

    [Column("RY_PublishedDate", TypeName = "date")]
    public DateTime? RyPublishedDate { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblReserchesAndFormsYearEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblReserchesAndFormsYearEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("RchId")]
    [InverseProperty("TblReserchesAndFormsYears")]
    public virtual TblResearchsAndForm Rch { get; set; }

    [InverseProperty("Ry")]
    public virtual ICollection<TblResearchLink> TblResearchLinks { get; set; } = new List<TblResearchLink>();

    [ForeignKey("YearId")]
    [InverseProperty("TblReserchesAndFormsYears")]
    public virtual TblYear Year { get; set; }
}