// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblRequestStatus")]
public partial class TblRequestStatus
{
    [Key]
    [Column("RS_ID")]
    public int RsId { get; set; }

    [Column("RS_NameAr")]
    [StringLength(50)]
    public string RsNameAr { get; set; }

    [Column("RS_NameEn")]
    [StringLength(50)]
    public string RsNameEn { get; set; }

    [InverseProperty("Rs")]
    public virtual ICollection<TblRequestRegisteration> TblRequestRegisterations { get; set; } = new List<TblRequestRegisteration>();
}