// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblRequestFormStatistican")]
public partial class TblRequestFormStatistican
{
    [Key]
    [Column("RFST_ID")]
    public int RfstId { get; set; }

    [Column("RFST_CreatedDate", TypeName = "datetime")]
    public DateTime? RfstCreatedDate { get; set; }

    [Column("RFST_StName")]
    [StringLength(100)]
    public string RfstStName { get; set; }

    [Column("RFST_Clarify")]
    [StringLength(100)]
    public string RfstClarify { get; set; }

    [Column("RFST_Employment")]
    [StringLength(100)]
    public string RfstEmployment { get; set; }

    [Column("RFST_Addreess")]
    [StringLength(250)]
    public string RfstAddreess { get; set; }

    [Column("RFST_PhoneNo")]
    [StringLength(50)]
    public string RfstPhoneNo { get; set; }

    [Column("RFST_MobileNo")]
    [StringLength(50)]
    public string RfstMobileNo { get; set; }

    [Column("RFST_FaxNo")]
    [StringLength(50)]
    public string RfstFaxNo { get; set; }

    [Column("RFST_EMail")]
    [StringLength(50)]
    public string RfstEmail { get; set; }

    [Column("RFST_SideName")]
    [StringLength(100)]
    public string RfstSideName { get; set; }

    [Column("RFST_ResaechTitle")]
    [StringLength(150)]
    public string RfstResaechTitle { get; set; }

    [Column("RFST_ReserachGoal")]
    public string RfstReserachGoal { get; set; }

    [Column("RFST_DocumentsNo")]
    [StringLength(150)]
    public string RfstDocumentsNo { get; set; }

    [Column("RFST_Society")]
    [StringLength(100)]
    public string RfstSociety { get; set; }

    [Column("RFST_SampleSize")]
    [StringLength(50)]
    public string RfstSampleSize { get; set; }

    [Column("RFST_StudyPeriod")]
    [StringLength(50)]
    public string RfstStudyPeriod { get; set; }

    [Column("RFST_Director")]
    [StringLength(100)]
    public string RfstDirector { get; set; }

    [Column("RFST_DirectEmp")]
    [StringLength(50)]
    public string RfstDirectEmp { get; set; }

    [Column("RFST_DirectPhone")]
    [StringLength(50)]
    public string RfstDirectPhone { get; set; }

    [Column("RFST_UserID")]
    public int? RfstUserId { get; set; }
}