// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblStatisticsBulltinsSectors")]
public partial class TblStatisticsBulltinsSector
{
    [Key]
    [Column("SBS_ID")]
    public int SbsId { get; set; }

    [Column("SBS_ArName")]
    [StringLength(100)]
    public string SbsArName { get; set; }

    [Column("SBS_EnName")]
    [StringLength(100)]
    public string SbsEnName { get; set; }

    [Column("SBS_Visable")]
    public bool? SbsVisable { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblStatisticsBulltinsSectorEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblStatisticsBulltinsSectorEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [InverseProperty("Sbs")]
    public virtual ICollection<TblStatisticsBulltinsSectoreDatum> TblStatisticsBulltinsSectoreData { get; set; } = new List<TblStatisticsBulltinsSectoreDatum>();
}