// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblStatistics_Categories")]
public partial class TblStatisticsCategory
{
    [Key]
    [Column("SC_ID")]
    public int ScId { get; set; }

    [Column("SC_NameAr")]
    [StringLength(100)]
    public string ScNameAr { get; set; }

    [Column("SC_NameEn")]
    [StringLength(100)]
    public string ScNameEn { get; set; }

    [Column("SC_Visible")]
    public bool? ScVisible { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [InverseProperty("Sc")]
    public virtual ICollection<TblStatisticsBulltin> TblStatisticsBulltins { get; set; } = new List<TblStatisticsBulltin>();
}