// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblStatisticsBulltinsSectoreData")]
[Index("SbyId", Name = "IX_tblStatisticsBulltinsSectoreData_SBY_ID")]
public partial class TblStatisticsBulltinsSectoreDatum
{
    [Key]
    [Column("SBSD_ID")]
    public int SbsdId { get; set; }

    [Column("SBS_ID")]
    public int? SbsId { get; set; }

    [Column("SBY_ID")]
    public int? SbyId { get; set; }

    [Column("SBSD_ArData")]
    public string SbsdArData { get; set; }

    [Column("SBSD_EnData")]
    public string SbsdEnData { get; set; }

    [Column("SBSD_LinkAr")]
    public string SbsdLinkAr { get; set; }

    [Column("SBSD_LinkEn")]
    public string SbsdLinkEn { get; set; }

    [Column("SBSD_Visable")]
    public bool? SbsdVisable { get; set; }

    [Column("SBSD_VisableEnglish")]
    public bool? SbsdVisableEnglish { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblStatisticsBulltinsSectoreDatumEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblStatisticsBulltinsSectoreDatumEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("SbsId")]
    [InverseProperty("TblStatisticsBulltinsSectoreData")]
    public virtual TblStatisticsBulltinsSector Sbs { get; set; }

    [ForeignKey("SbyId")]
    [InverseProperty("TblStatisticsBulltinsSectoreData")]
    public virtual TblStatistcalBulltinsYear Sby { get; set; }
}