// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblStatistcalBulltinsYear")]
[Index("HcaId", Name = "IX_tblStatistcalBulltinsYear_HCA_ID")]
[Index("HcaId", "SbyId", Name = "IX_tblStatistcalBulltinsYear_HCA_ID_SBY_ID")]
[Index("SbyVisable", Name = "IX_tblStatistcalBulltinsYear_SBY_Visable")]
[Index("SbyVisable", "SbId", Name = "IX_tblStatistcalBulltinsYear_SBY_Visable_SB_ID")]
[Index("SbyVisable", "SbId", "SbyPublishedDate", "SbyHardCopy", Name = "IX_tblStatistcalBulltinsYear_SBY_Visable_SB_ID_SBY_PublishedDate_SBY_HardCopy")]
[Index("SbId", Name = "IX_tblStatistcalBulltinsYear_SB_ID")]
[Index("SbId", "SbyPublishedDate", "SbyHardCopy", Name = "IX_tblStatistcalBulltinsYear_SB_ID_SBY_PublishedDate_SBY_HardCopy")]
[Index("YearId", Name = "IX_tblStatistcalBulltinsYear_Year_ID")]
public partial class TblStatistcalBulltinsYear
{
    [Key]
    [Column("SBY_ID")]
    public int SbyId { get; set; }

    [Column("CBY_CreatedDate", TypeName = "datetime")]
    public DateTime? CbyCreatedDate { get; set; }

    [Column("SBY_Visable")]
    public bool? SbyVisable { get; set; }

    [Column("SBY_Link")]
    public string SbyLink { get; set; }

    [Column("SBY_YearlyBookPage")]
    public string SbyYearlyBookPage { get; set; }

    [Column("SBY_StatsticalGlance")]
    public string SbyStatsticalGlance { get; set; }

    [Column("SBY_EgyptInFigures")]
    public string SbyEgyptInFigures { get; set; }

    [Column("SBY_PublishedDate", TypeName = "date")]
    public DateTime SbyPublishedDate { get; set; }

    [Column("SBY_NextPublishDate")]
    [StringLength(50)]
    public string SbyNextPublishDate { get; set; }

    [Column("Year_ID")]
    public int? YearId { get; set; }

    [Column("SB_ID")]
    public int? SbId { get; set; }

    [Column("SBY_OracleID")]
    public int? SbyOracleId { get; set; }

    [Column("Month_ID")]
    public int? MonthId { get; set; }

    [Column("SBY_BriefAr")]
    public string SbyBriefAr { get; set; }

    [Column("SBY_BriefEn")]
    public string SbyBriefEn { get; set; }

    [Column("SBY_MainTopicsAr")]
    public string SbyMainTopicsAr { get; set; }

    [Column("SBY_MainTopicsEn")]
    public string SbyMainTopicsEn { get; set; }

    [Column("SBY_Restricted")]
    public bool? SbyRestricted { get; set; }

    [Column("SBY_InternalShow")]
    public bool? SbyInternalShow { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("SBY_LoginedUser")]
    public bool? SbyLoginedUser { get; set; }

    [Column("SBY_CoverImage")]
    [StringLength(150)]
    public string SbyCoverImage { get; set; }

    [Column("SBY_Price", TypeName = "decimal(18, 2)")]
    public decimal? SbyPrice { get; set; }

    [Column("SBY_HardCopy")]
    public bool? SbyHardCopy { get; set; }

    [Column("HCA_ID")]
    public int? HcaId { get; set; }

    [Column("SBY_ShowInMain")]
    public bool? SbyShowInMain { get; set; }

    [Column("SBY_Cat")]
    public int? SbyCat { get; set; }

    [Column("SBY_Price_old", TypeName = "decimal(18, 2)")]
    public decimal? SbyPriceOld { get; set; }

    [Column("SBY_Price_4_22", TypeName = "numeric(18, 2)")]
    public decimal? SbyPrice422 { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblStatistcalBulltinsYearEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblStatistcalBulltinsYearEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("HcaId")]
    [InverseProperty("TblStatistcalBulltinsYears")]
    public virtual HistoryDetail Hca { get; set; }

    [ForeignKey("MonthId")]
    [InverseProperty("TblStatistcalBulltinsYears")]
    public virtual TblMonth Month { get; set; }

    [ForeignKey("SbId")]
    [InverseProperty("TblStatistcalBulltinsYears")]
    public virtual TblStatisticsBulltin Sb { get; set; }

    [InverseProperty("Sby")]
    public virtual ICollection<TblStatisticsBulltinsSectoreDatum> TblStatisticsBulltinsSectoreData { get; set; } = new List<TblStatisticsBulltinsSectoreDatum>();

    [ForeignKey("YearId")]
    [InverseProperty("TblStatistcalBulltinsYears")]
    public virtual TblYear Year { get; set; }
}