// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblStatisticsDepartements")]
public partial class TblStatisticsDepartement
{
    [Key]
    [Column("SD_ID")]
    public int SdId { get; set; }

    [Column("SD_OracleID")]
    public int SdOracleId { get; set; }

    [Required]
    [Column("SD_ArName")]
    [StringLength(150)]
    public string SdArName { get; set; }

    [Required]
    [Column("SD_EnName")]
    [StringLength(150)]
    public string SdEnName { get; set; }

    [Required]
    [Column("SD_Visable")]
    public bool? SdVisable { get; set; }

    [Column("MSM_ID")]
    public int? MsmId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblStatisticsDepartementEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblStatisticsDepartementEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [InverseProperty("Sd")]
    public virtual ICollection<HistoryCategorySub> HistoryCategorySubs { get; set; } = new List<HistoryCategorySub>();

    [ForeignKey("MsmId")]
    [InverseProperty("TblStatisticsDepartements")]
    public virtual TblMainSubMenu Msm { get; set; }

    [InverseProperty("Sd")]
    public virtual ICollection<TblFaq> TblFaqs { get; set; } = new List<TblFaq>();

    [InverseProperty("Sd")]
    public virtual ICollection<TblStatisticsBulltin> TblStatisticsBulltins { get; set; } = new List<TblStatisticsBulltin>();
}