// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblSmartTVImages")]
public partial class TblSmartTvimage
{
    [Key]
    [Column("Img_ID")]
    public int ImgId { get; set; }

    [Column("Img_Name")]
    [StringLength(50)]
    public string ImgName { get; set; }

    [Column("Img_Path")]
    [StringLength(150)]
    public string ImgPath { get; set; }

    [InverseProperty("Img")]
    public virtual ICollection<TblSmartTvindicator> TblSmartTvindicators { get; set; } = new List<TblSmartTvindicator>();
}