// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblSiteCategories")]
public partial class TblSiteCategory
{
    [Key]
    [Column("SC_ID")]
    public int ScId { get; set; }

    [Column("SC_NameAr")]
    [StringLength(50)]
    public string ScNameAr { get; set; }

    [Column("SC_NameEn")]
    [StringLength(50)]
    public string ScNameEn { get; set; }

    [Column("MSM_ID")]
    public int? MsmId { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblSiteCategoryEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblSiteCategoryEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("MsmId")]
    [InverseProperty("TblSiteCategories")]
    public virtual TblMainSubMenu Msm { get; set; }

    [InverseProperty("Sc")]
    public virtual ICollection<TblSite> TblSites { get; set; } = new List<TblSite>();
}