// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblSites")]
public partial class TblSite
{
    [Key]
    [Column("Sit_ID")]
    public int SitId { get; set; }

    [Column("SC_ID")]
    public int? ScId { get; set; }

    [Column("Sit_TitleAr")]
    [StringLength(200)]
    public string SitTitleAr { get; set; }

    [Column("Sit_TitleEn")]
    [StringLength(200)]
    public string SitTitleEn { get; set; }

    [Column("Sit_IconLink")]
    [StringLength(200)]
    public string SitIconLink { get; set; }

    [Column("Sit_LinkAr")]
    [StringLength(200)]
    public string SitLinkAr { get; set; }

    [Column("Sit_LinkEn")]
    [StringLength(200)]
    public string SitLinkEn { get; set; }

    [Column("Sit_DescAr")]
    [StringLength(500)]
    public string SitDescAr { get; set; }

    [Column("Sit_DescEn")]
    [StringLength(500)]
    public string SitDescEn { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("Sit_Visible")]
    public bool? SitVisible { get; set; }

    [Column("Sit_ShowInMain")]
    public bool? SitShowInMain { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblSiteEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblSiteEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [ForeignKey("ScId")]
    [InverseProperty("TblSites")]
    public virtual TblSiteCategory Sc { get; set; }
}