// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblUserTypes")]
public partial class TblUserType
{
    [Key]
    [Column("UT_ID")]
    public int UtId { get; set; }

    [Column("UT_Name")]
    [StringLength(50)]
    public string UtName { get; set; }

    [InverseProperty("Ut")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}