// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblUserGroups")]
public partial class TblUserGroup
{
    [Key]
    [Column("UsrGrp_ID")]
    public int UsrGrpId { get; set; }

    [Column("UsrGrp_NameAr")]
    [StringLength(100)]
    public string UsrGrpNameAr { get; set; }

    [Column("UsrGrp_NameEn")]
    [StringLength(100)]
    public string UsrGrpNameEn { get; set; }

    [Column("UsrGrp_Paid")]
    public bool? UsrGrpPaid { get; set; }

    [Column("Emp_Create")]
    public int? EmpCreate { get; set; }

    [Column("Emp_Last_Update")]
    public int? EmpLastUpdate { get; set; }

    [Column("Emp_Update_Date", TypeName = "datetime")]
    public DateTime? EmpUpdateDate { get; set; }

    [Column("UsrGrp_ArMassage")]
    [StringLength(150)]
    public string UsrGrpArMassage { get; set; }

    [Column("UsrGrp_EnMassage")]
    [StringLength(150)]
    public string UsrGrpEnMassage { get; set; }

    [ForeignKey("EmpCreate")]
    [InverseProperty("TblUserGroupEmpCreateNavigations")]
    public virtual TblEmployee EmpCreateNavigation { get; set; }

    [ForeignKey("EmpLastUpdate")]
    [InverseProperty("TblUserGroupEmpLastUpdateNavigations")]
    public virtual TblEmployee EmpLastUpdateNavigation { get; set; }

    [InverseProperty("UsrGrp")]
    public virtual ICollection<TblUser> TblUserUsrGrps { get; set; } = new List<TblUser>();

    [InverseProperty("UsrRegisterdGroupNavigation")]
    public virtual ICollection<TblUser> TblUserUsrRegisterdGroupNavigations { get; set; } = new List<TblUser>();

    [InverseProperty("UsrGrp")]
    public virtual ICollection<TblUsersGroupsBulltin> TblUsersGroupsBulltins { get; set; } = new List<TblUsersGroupsBulltin>();
}