// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblUseMessages")]
public partial class TblUseMessage
{
    [Key]
    [Column("UsrMsg_ID")]
    public int UsrMsgId { get; set; }

    [Column("Msg_ID")]
    public int? MsgId { get; set; }

    [Column("UsrMsg_Link")]
    [StringLength(150)]
    public string UsrMsgLink { get; set; }

    [Column("UsrMsg_date", TypeName = "datetime")]
    public DateTime? UsrMsgDate { get; set; }

    [Column("UsrMsg_Showen")]
    public bool? UsrMsgShowen { get; set; }

    [Column("Que_ID")]
    public int? QueId { get; set; }

    [Column("Usr_ID")]
    public int? UsrId { get; set; }

    [ForeignKey("MsgId")]
    [InverseProperty("TblUseMessages")]
    public virtual TblMessage Msg { get; set; }

    [ForeignKey("QueId")]
    [InverseProperty("TblUseMessages")]
    public virtual TblQuestion Que { get; set; }

    [ForeignKey("UsrId")]
    [InverseProperty("TblUseMessages")]
    public virtual TblUser Usr { get; set; }
}