// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblUsersAnswers")]
public partial class TblUsersAnswer
{
    [Key]
    [Column("UA_ID")]
    public int UaId { get; set; }

    [Column("UA_Answer")]
    [StringLength(500)]
    public string UaAnswer { get; set; }

    [Column("Emp_ID")]
    public int? EmpId { get; set; }

    [Column("UA_IsVisible")]
    public bool? UaIsVisible { get; set; }

    [Column("Usr_ID")]
    public int? UsrId { get; set; }

    [Column("DT_ID")]
    public int? DtId { get; set; }

    [Column("UA_CreatedDate", TypeName = "datetime")]
    public DateTime? UaCreatedDate { get; set; }

    [ForeignKey("DtId")]
    [InverseProperty("TblUsersAnswers")]
    public virtual TblDisscutionTopic Dt { get; set; }

    [ForeignKey("EmpId")]
    [InverseProperty("TblUsersAnswers")]
    public virtual TblEmployee Emp { get; set; }

    [ForeignKey("UsrId")]
    [InverseProperty("TblUsersAnswers")]
    public virtual TblUser Usr { get; set; }
}