// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblVisits_Logs")]
[Index("EnglishPage", Name = "IX_tblVisits_Logs_English_Page")]
[Index("ItemId", "ItemType", "VisDate", Name = "IX_tblVisits_Logs_Item_ID_Item_Type_Vis_Date")]
[Index("ItemId", "VisDate", "PublName", Name = "IX_tblVisits_Logs_Item_ID_Vis_Date_Publ_Name")]
[Index("VisDate", "EnglishPage", Name = "IX_tblVisits_Logs_Vis_Date_English_Page")]
[Index("VisDate", "PublName", Name = "IX_tblVisits_Logs_Vis_Date_Publ_Name")]
public partial class TblVisitsLog
{
    [Key]
    [Column("Vis_ID")]
    public long VisId { get; set; }

    [Column("Usr_ID")]
    public int? UsrId { get; set; }

    [Column("Vis_Date", TypeName = "datetime")]
    public DateTime? VisDate { get; set; }

    [Column("Vis_URL")]
    public string VisUrl { get; set; }

    [Column("Vis_IP")]
    [StringLength(50)]
    public string VisIp { get; set; }

    [Column("Publ_Name")]
    [StringLength(150)]
    public string PublName { get; set; }

    [Column("Item_ID")]
    public int? ItemId { get; set; }

    [Column("Item_Type")]
    [StringLength(2)]
    public string ItemType { get; set; }

    [Column("English_Page")]
    public bool? EnglishPage { get; set; }
}