// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("tblYearsNew")]
public partial class TblYearsNew
{
    [Column("Year_ID")]
    public int YearId { get; set; }

    [Column("Year_Name")]
    [StringLength(9)]
    public string YearName { get; set; }

    [Column("Year_Fin_ED")]
    public bool? YearFinEd { get; set; }
}