// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("tblYears")]
public partial class TblYear
{
    [Key]
    [Column("Year_ID")]
    public int YearId { get; set; }

    [Column("Year_Name")]
    [StringLength(9)]
    public string YearName { get; set; }

    [Column("Year_Fin_ED")]
    public bool? YearFinEd { get; set; }

    [InverseProperty("Year")]
    public virtual ICollection<HistoryDetail> HistoryDetails { get; set; } = new List<HistoryDetail>();

    [InverseProperty("Year")]
    public virtual ICollection<TblIndicatorDatum> TblIndicatorData { get; set; } = new List<TblIndicatorDatum>();

    [InverseProperty("Year")]
    public virtual ICollection<TblInternationalIndicatorsDetail> TblInternationalIndicatorsDetails { get; set; } = new List<TblInternationalIndicatorsDetail>();

    [InverseProperty("Year")]
    public virtual ICollection<TblReserchesAndFormsYear> TblReserchesAndFormsYears { get; set; } = new List<TblReserchesAndFormsYear>();

    [InverseProperty("Year")]
    public virtual ICollection<TblStatistcalBulltinsYear> TblStatistcalBulltinsYears { get; set; } = new List<TblStatistcalBulltinsYear>();
}