// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_MANUFACTURE")]
public partial class TradeForManufacture
{
    [Key]
    [Column("MANUFACTURE_ID", TypeName = "numeric(38, 0)")]
    public decimal ManufactureId { get; set; }

    [Column("MANUFACTURE_NAMEAR")]
    [StringLength(100)]
    public string ManufactureNamear { get; set; }

    [Column("MANUFACTURE_NAMEEN")]
    [StringLength(116)]
    public string ManufactureNameen { get; set; }

    [Column("MANUFACTURE_CODE")]
    [StringLength(4)]
    public string ManufactureCode { get; set; }

    [InverseProperty("ManufactureExport")]
    public virtual ICollection<TradeForHsn> TradeForHsnManufactureExports { get; set; } = new List<TradeForHsn>();

    [InverseProperty("ManufactureImport")]
    public virtual ICollection<TradeForHsn> TradeForHsnManufactureImports { get; set; } = new List<TradeForHsn>();
}