// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("TRADE_FOR_EXP_ROWDATANew")]
public partial class TradeForExpRowdatanew
{
    [Column("ROWDATA_ID")]
    public int RowdataId { get; set; }

    [Column("TBLN_ID")]
    public int? TblnId { get; set; }

    [Column("TRADE_FOR_COUNTRY_ID")]
    public int? TradeForCountryId { get; set; }

    [Column("TRADE_FOR_UNITS_ID")]
    public int? TradeForUnitsId { get; set; }

    [Column("TRADE_FOR_PORTS_ID")]
    public int? TradeForPortsId { get; set; }

    [Column("TRADE_FOR_CHAPTERS_ID")]
    public int? TradeForChaptersId { get; set; }

    [Column("TRADE_FOR_SUB_CHAPTERS_ID")]
    public int? TradeForSubChaptersId { get; set; }

    [Column("TRADE_FOR_HSN_ID")]
    public int? TradeForHsnId { get; set; }

    [Column("TRADE_FOR_MANUFACTURE_ID")]
    public int? TradeForManufactureId { get; set; }

    [Column("COL1")]
    [StringLength(20)]
    public string Col1 { get; set; }

    [Column("COL2")]
    [StringLength(20)]
    public string Col2 { get; set; }

    [Column("COL3")]
    [StringLength(20)]
    public string Col3 { get; set; }

    [Column("COL4")]
    [StringLength(20)]
    public string Col4 { get; set; }

    [Column("COL5")]
    [StringLength(20)]
    public string Col5 { get; set; }

    [Column("COL6")]
    [StringLength(20)]
    public string Col6 { get; set; }

    [Column("COL7")]
    [StringLength(20)]
    public string Col7 { get; set; }

    [Column("COL8")]
    [StringLength(20)]
    public string Col8 { get; set; }

    [Column("COL9")]
    [StringLength(20)]
    public string Col9 { get; set; }

    [Column("COL10")]
    [StringLength(20)]
    public string Col10 { get; set; }

    [Column("COL11")]
    [StringLength(20)]
    public string Col11 { get; set; }

    [Column("COL12")]
    [StringLength(20)]
    public string Col12 { get; set; }

    [Column("COL13")]
    [StringLength(20)]
    public string Col13 { get; set; }

    [Column("COL14")]
    [StringLength(20)]
    public string Col14 { get; set; }

    [Column("COL15")]
    [StringLength(20)]
    public string Col15 { get; set; }

    [Column("COL16")]
    [StringLength(20)]
    public string Col16 { get; set; }

    [Column("COL17")]
    [StringLength(20)]
    public string Col17 { get; set; }

    [Column("COL18")]
    [StringLength(20)]
    public string Col18 { get; set; }

    [Column("COL19")]
    [StringLength(20)]
    public string Col19 { get; set; }

    [Column("COL20")]
    [StringLength(20)]
    public string Col20 { get; set; }

    [Column("COL21")]
    [StringLength(20)]
    public string Col21 { get; set; }

    [Column("COL22")]
    [StringLength(20)]
    public string Col22 { get; set; }

    [Column("COL23")]
    [StringLength(20)]
    public string Col23 { get; set; }

    [Column("COL24")]
    [StringLength(20)]
    public string Col24 { get; set; }

    [Column("COL25")]
    [StringLength(20)]
    public string Col25 { get; set; }

    [Column("COL26")]
    [StringLength(20)]
    public string Col26 { get; set; }

    [Column("COL27")]
    [StringLength(20)]
    public string Col27 { get; set; }

    [Column("COL28")]
    [StringLength(20)]
    public string Col28 { get; set; }

    [Column("COL29")]
    [StringLength(20)]
    public string Col29 { get; set; }

    [Column("COL30")]
    [StringLength(20)]
    public string Col30 { get; set; }

    [Column("DAT")]
    public int? Dat { get; set; }

    [Column("DOLLAR_SIGN")]
    [StringLength(20)]
    public string DollarSign { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID")]
    public int? GeneralTablesTypesId { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID2")]
    public int? GeneralTablesTypesId2 { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID3")]
    public int? GeneralTablesTypesId3 { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID4")]
    public int? GeneralTablesTypesId4 { get; set; }

    [ForeignKey("Dat")]
    public virtual TradeForFdollernew DatNavigation { get; set; }

    [ForeignKey("TradeForChaptersId")]
    public virtual TradeForChaptersnew TradeForChapters { get; set; }

    [ForeignKey("TradeForChaptersId")]
    public virtual TradeForSubChaptersnew TradeForChaptersNavigation { get; set; }

    [ForeignKey("TradeForCountryId")]
    public virtual TradeForCountrynew TradeForCountry { get; set; }

    [ForeignKey("TradeForHsnId")]
    public virtual TradeForHsnnew TradeForHsn { get; set; }

    [ForeignKey("TradeForManufactureId")]
    public virtual TradeForManufacturenew TradeForManufacture { get; set; }

    [ForeignKey("TradeForPortsId")]
    public virtual TradeForPortsnew TradeForPorts { get; set; }

    [ForeignKey("TradeForUnitsId")]
    public virtual TradeForUnitsnew TradeForUnits { get; set; }
}