// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_SUB_CHAPTERS")]
public partial class TradeForSubChapter
{
    [Key]
    [Column("SUB_CHAPTERS_ID", TypeName = "numeric(38, 0)")]
    public decimal SubChaptersId { get; set; }

    [Column("SUB_CHAPTERS_NAMEAR")]
    [StringLength(500)]
    public string SubChaptersNamear { get; set; }

    [Column("SUB_CHAPTERS_NAMEEN")]
    [StringLength(500)]
    public string SubChaptersNameen { get; set; }

    [Column("SUB_CHAPTERS_CODE")]
    [StringLength(8)]
    public string SubChaptersCode { get; set; }

    [InverseProperty("SubChapters")]
    public virtual ICollection<TradeForHsn> TradeForHsns { get; set; } = new List<TradeForHsn>();
}