// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("TRADE_FOR_IMP_ROWDATA")]
public partial class TradeForImpRowdatum
{
    [Column("ROWDATA_ID", TypeName = "numeric(38, 0)")]
    public decimal RowdataId { get; set; }

    [Column("TBLN_ID", TypeName = "numeric(38, 0)")]
    public decimal? TblnId { get; set; }

    [Column("TRADE_FOR_COUNTRY_ID", TypeName = "numeric(38, 0)")]
    public decimal? TradeForCountryId { get; set; }

    [Column("TRADE_FOR_UNITS_ID", TypeName = "numeric(38, 0)")]
    public decimal? TradeForUnitsId { get; set; }

    [Column("TRADE_FOR_PORTS_ID", TypeName = "numeric(38, 0)")]
    public decimal? TradeForPortsId { get; set; }

    [Column("TRADE_FOR_CHAPTERS_ID", TypeName = "numeric(38, 0)")]
    public decimal? TradeForChaptersId { get; set; }

    [Column("TRADE_FOR_SUB_CHAPTERS_ID", TypeName = "numeric(38, 0)")]
    public decimal? TradeForSubChaptersId { get; set; }

    [Column("TRADE_FOR_HSN_ID", TypeName = "numeric(38, 0)")]
    public decimal? TradeForHsnId { get; set; }

    [Column("TRADE_FOR_MANUFACTURE_ID", TypeName = "numeric(38, 0)")]
    public decimal? TradeForManufactureId { get; set; }

    [Column("COL1")]
    [StringLength(40)]
    public string Col1 { get; set; }

    [Column("COL2")]
    [StringLength(40)]
    public string Col2 { get; set; }

    [Column("COL3")]
    [StringLength(40)]
    public string Col3 { get; set; }

    [Column("COL4")]
    [StringLength(40)]
    public string Col4 { get; set; }

    [Column("COL5")]
    [StringLength(40)]
    public string Col5 { get; set; }

    [Column("COL6")]
    [StringLength(40)]
    public string Col6 { get; set; }

    [Column("COL7")]
    [StringLength(40)]
    public string Col7 { get; set; }

    [Column("COL8")]
    [StringLength(40)]
    public string Col8 { get; set; }

    [Column("COL9")]
    [StringLength(40)]
    public string Col9 { get; set; }

    [Column("COL10")]
    [StringLength(40)]
    public string Col10 { get; set; }

    [Column("COL11")]
    [StringLength(40)]
    public string Col11 { get; set; }

    [Column("COL12")]
    [StringLength(40)]
    public string Col12 { get; set; }

    [Column("COL13")]
    [StringLength(40)]
    public string Col13 { get; set; }

    [Column("COL14")]
    [StringLength(40)]
    public string Col14 { get; set; }

    [Column("COL15")]
    [StringLength(40)]
    public string Col15 { get; set; }

    [Column("COL16")]
    [StringLength(40)]
    public string Col16 { get; set; }

    [Column("COL17")]
    [StringLength(40)]
    public string Col17 { get; set; }

    [Column("COL18")]
    [StringLength(40)]
    public string Col18 { get; set; }

    [Column("COL19")]
    [StringLength(40)]
    public string Col19 { get; set; }

    [Column("COL20")]
    [StringLength(40)]
    public string Col20 { get; set; }

    [Column("COL21")]
    [StringLength(40)]
    public string Col21 { get; set; }

    [Column("COL22")]
    [StringLength(40)]
    public string Col22 { get; set; }

    [Column("COL23")]
    [StringLength(40)]
    public string Col23 { get; set; }

    [Column("COL24")]
    [StringLength(40)]
    public string Col24 { get; set; }

    [Column("COL25")]
    [StringLength(40)]
    public string Col25 { get; set; }

    [Column("COL26")]
    [StringLength(40)]
    public string Col26 { get; set; }

    [Column("COL27")]
    [StringLength(40)]
    public string Col27 { get; set; }

    [Column("COL28")]
    [StringLength(40)]
    public string Col28 { get; set; }

    [Column("COL29")]
    [StringLength(40)]
    public string Col29 { get; set; }

    [Column("COL30")]
    [StringLength(40)]
    public string Col30 { get; set; }

    [Column("DAT", TypeName = "numeric(38, 0)")]
    public decimal? Dat { get; set; }

    [Column("DOLLAR_SIGN")]
    [StringLength(40)]
    public string DollarSign { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID", TypeName = "numeric(38, 0)")]
    public decimal? GeneralTablesTypesId { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID2", TypeName = "numeric(38, 0)")]
    public decimal? GeneralTablesTypesId2 { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID3", TypeName = "numeric(38, 0)")]
    public decimal? GeneralTablesTypesId3 { get; set; }

    [Column("GENERAL_TABLES_TYPES_ID4", TypeName = "numeric(38, 0)")]
    public decimal? GeneralTablesTypesId4 { get; set; }

    [ForeignKey("Dat")]
    public virtual TradeForFdoller DatNavigation { get; set; }

    [ForeignKey("TradeForChaptersId")]
    public virtual TradeForChapter TradeForChapters { get; set; }

    [ForeignKey("TradeForCountryId")]
    public virtual TradeForCountry TradeForCountry { get; set; }

    [ForeignKey("TradeForHsnId")]
    public virtual TradeForHsn TradeForHsn { get; set; }

    [ForeignKey("TradeForManufactureId")]
    public virtual TradeForManufacture TradeForManufacture { get; set; }

    [ForeignKey("TradeForPortsId")]
    public virtual TradeForPort TradeForPorts { get; set; }

    [ForeignKey("TradeForSubChaptersId")]
    public virtual TradeForSubChapter TradeForSubChapters { get; set; }

    [ForeignKey("TradeForUnitsId")]
    public virtual TradeForUnit TradeForUnits { get; set; }
}