// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_MANUFACTURENew")]
public partial class TradeForManufacturenew
{
    [Key]
    [Column("MANUFACTURE_ID")]
    public int ManufactureId { get; set; }

    [Column("MANUFACTURE_NAMEAR")]
    [StringLength(50)]
    public string ManufactureNamear { get; set; }

    [Column("MANUFACTURE_NAMEEN")]
    [StringLength(50)]
    public string ManufactureNameen { get; set; }

    [Column("MANUFACTURE_CODE")]
    [StringLength(2)]
    public string ManufactureCode { get; set; }
}