// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_PORTSNew")]
public partial class TradeForPortsnew
{
    [Key]
    [Column("PORTS_ID")]
    public int PortsId { get; set; }

    [Column("PORTS_NAMEAR")]
    [StringLength(150)]
    public string PortsNamear { get; set; }

    [Column("PORTS_NAMEEN")]
    [StringLength(150)]
    public string PortsNameen { get; set; }

    [Column("PORTS_CODE")]
    [StringLength(2)]
    public string PortsCode { get; set; }
}