// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_FDOLLER")]
public partial class TradeForFdoller
{
    [Key]
    [Column("DAT", TypeName = "numeric(38, 0)")]
    public decimal Dat { get; set; }

    [Column("DOLLER", TypeName = "numeric(38, 0)")]
    public decimal? Doller { get; set; }
}