// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_UNITSNew")]
public partial class TradeForUnitsnew
{
    [Key]
    [Column("UNITS_ID")]
    public int UnitsId { get; set; }

    [Column("UNITS_NAMEAR")]
    [StringLength(150)]
    public string UnitsNamear { get; set; }

    [Column("UNITS_NAMEEN")]
    [StringLength(150)]
    public string UnitsNameen { get; set; }

    [Column("UNITS_COOD")]
    [StringLength(6)]
    public string UnitsCood { get; set; }
}