// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_SUB_CHAPTERSNew")]
public partial class TradeForSubChaptersnew
{
    [Key]
    [Column("SUB_CHAPTERS_ID")]
    public int SubChaptersId { get; set; }

    [Column("SUB_CHAPTERS_NAMEAR")]
    [StringLength(250)]
    public string SubChaptersNamear { get; set; }

    [Column("SUB_CHAPTERS_NAMEEN")]
    [StringLength(250)]
    public string SubChaptersNameen { get; set; }

    [Column("SUB_CHAPTERS_CODE")]
    [StringLength(4)]
    public string SubChaptersCode { get; set; }
}