// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_UNITS")]
public partial class TradeForUnit
{
    [Key]
    [Column("UNITS_ID", TypeName = "numeric(38, 0)")]
    public decimal UnitsId { get; set; }

    [Column("UNITS_NAMEAR")]
    [StringLength(300)]
    public string UnitsNamear { get; set; }

    [Column("UNITS_NAMEEN")]
    [StringLength(300)]
    public string UnitsNameen { get; set; }

    [Column("UNITS_COOD")]
    [StringLength(12)]
    public string UnitsCood { get; set; }

    [InverseProperty("Units")]
    public virtual ICollection<TradeForHsn> TradeForHsns { get; set; } = new List<TradeForHsn>();
}