// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("TRADE_NAMEIMEX2008")]
public partial class TradeNameimex2008
{
    [Required]
    [Column("CODE")]
    [StringLength(9)]
    [Unicode(false)]
    public string Code { get; set; }

    [Column("NAME")]
    [StringLength(400)]
    public string Name { get; set; }

    [Column("ADDRESS")]
    [StringLength(400)]
    public string Address { get; set; }
}