// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_FDOLLERNew")]
public partial class TradeForFdollernew
{
    [Key]
    [Column("DAT")]
    public int Dat { get; set; }

    [Column("DOLLER")]
    public int? Doller { get; set; }
}