// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("TRADE_FOR_BALANCENew")]
public partial class TradeForBalancenew
{
    [Column("DAT")]
    public int? Dat { get; set; }

    [Column("TRADE_FOR_COUNTRY_ID")]
    public int? TradeForCountryId { get; set; }

    [Column("EXPV", TypeName = "decimal(18, 0)")]
    public decimal? Expv { get; set; }

    [Column("EXPQ", TypeName = "decimal(18, 0)")]
    public decimal? Expq { get; set; }

    [Column("IMPV", TypeName = "decimal(18, 0)")]
    public decimal? Impv { get; set; }

    [Column("IMPQ", TypeName = "decimal(18, 0)")]
    public decimal? Impq { get; set; }

    [Column("TRADE_FOR_BLANCE_ID")]
    public int TradeForBlanceId { get; set; }

    [ForeignKey("Dat")]
    public virtual TradeForFdollernew DatNavigation { get; set; }

    [ForeignKey("TradeForCountryId")]
    public virtual TradeForCountrynew TradeForCountry { get; set; }
}