// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Table("TRADE_FOR_HSN")]
public partial class TradeForHsn
{
    [Key]
    [Column("HSN_ID", TypeName = "numeric(38, 0)")]
    public decimal HsnId { get; set; }

    [Column("HSN_NAMEAR")]
    [StringLength(600)]
    public string HsnNamear { get; set; }

    [Column("HSN_NAMEEN")]
    [StringLength(1400)]
    public string HsnNameen { get; set; }

    [Column("SUB_CHAPTERS_ID", TypeName = "numeric(38, 0)")]
    public decimal? SubChaptersId { get; set; }

    [Column("MANUFACTURE_IMPORT_ID", TypeName = "numeric(38, 0)")]
    public decimal? ManufactureImportId { get; set; }

    [Column("UNITS_ID", TypeName = "numeric(38, 0)")]
    public decimal? UnitsId { get; set; }

    [Column("HSN_CODE")]
    [StringLength(20)]
    public string HsnCode { get; set; }

    [Column("MANUFACTURE_EXPORT_ID", TypeName = "numeric(38, 0)")]
    public decimal? ManufactureExportId { get; set; }

    [ForeignKey("ManufactureExportId")]
    [InverseProperty("TradeForHsnManufactureExports")]
    public virtual TradeForManufacture ManufactureExport { get; set; }

    [ForeignKey("ManufactureImportId")]
    [InverseProperty("TradeForHsnManufactureImports")]
    public virtual TradeForManufacture ManufactureImport { get; set; }

    [ForeignKey("SubChaptersId")]
    [InverseProperty("TradeForHsns")]
    public virtual TradeForSubChapter SubChapters { get; set; }

    [ForeignKey("UnitsId")]
    [InverseProperty("TradeForHsns")]
    public virtual TradeForUnit Units { get; set; }
}