// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("translate_tblIndicatorGenSector")]
public partial class TranslateTblIndicatorGenSector
{
    [Column("GenSector_ID")]
    public int? GenSectorId { get; set; }

    [Column("GenSector_NameAr")]
    [StringLength(30)]
    public string GenSectorNameAr { get; set; }

    [Column("GenSector_NameEn")]
    [StringLength(30)]
    public string GenSectorNameEn { get; set; }
}