// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("translate_tblIndicatorGender")]
public partial class TranslateTblIndicatorGender
{
    [Column("Gen_ID")]
    public int? GenId { get; set; }

    [Column("Gen_NameAr")]
    [StringLength(10)]
    public string GenNameAr { get; set; }

    [Column("Gen_NameEn")]
    [StringLength(10)]
    public string GenNameEn { get; set; }
}