// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Context.Old_Models;

[Keyless]
[Table("translate_tblIndicatorLegalEntity")]
public partial class TranslateTblIndicatorLegalEntity
{
    [Column("LegalEntity_ID")]
    public int? LegalEntityId { get; set; }

    [Column("LegalEntity_NameAr")]
    [StringLength(40)]
    public string LegalEntityNameAr { get; set; }

    [Column("LegalEntity_NameEn")]
    [StringLength(40)]
    public string LegalEntityNameEn { get; set; }
}